import {createCipheriv,createDecipheriv,createHash,randomBytes,randomUUID,timingSafeEqual} from 'node:crypto';
import type {CoreRepository,CoreActor} from './types';
import type {SecretKind,SecretPayload,VaultSecret,SecretVaultState,RevealPolicy,VaultCipher,VaultAudit} from './secretVaultTypes';
import type {BookToolScope} from '../ai/tools/types';
import {CoreRuleError} from './rules';
import {parseCausalityPolicy,checkSecretReveal} from './causality';
import {scanScenes,sceneIsBefore} from './timeline';
import {cleanFragmentText} from './interviewProposals';
import {getBook} from '../bookStore';
import {mysteryKnowledge,mysteryRecommendation,rethrowMysteryInterruption} from './mysteryDirector';
export class VaultUnavailableError extends Error {constructor(){super('Vault недоступний: налаштуйте SECRET_VAULT_KEY_BASE64 у захищених змінних сервера.');}}
export function vaultKeyFromEnv(){const value=process.env.SECRET_VAULT_KEY_BASE64;if(!value||!/^[A-Za-z0-9+/]{43}=$/.test(value))throw new VaultUnavailableError();const key=Buffer.from(value,'base64');if(key.length!==32)throw new VaultUnavailableError();return key;}
function checkedKey(key:Buffer){if(!Buffer.isBuffer(key)||key.length!==32)throw new VaultUnavailableError();return key;}
const aad=(p:string,id:string,version:number)=>Buffer.from(JSON.stringify([p,id,version]));
export function encryptVault(key:Buffer,p:string,id:string,version:number,value:unknown):VaultCipher{const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',checkedKey(key),iv);cipher.setAAD(aad(p,id,version));const data=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return {iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),data:data.toString('base64')};}
export function decryptVault<T>(key:Buffer,p:string,id:string,version:number,value:VaultCipher):T{try{const cipher=createDecipheriv('aes-256-gcm',checkedKey(key),Buffer.from(value.iv,'base64'));cipher.setAAD(aad(p,id,version));cipher.setAuthTag(Buffer.from(value.tag,'base64'));return JSON.parse(Buffer.concat([cipher.update(Buffer.from(value.data,'base64')),cipher.final()]).toString('utf8'));}catch{throw new CoreRuleError('conflict','Не вдалося перевірити зашифрований Vault.');}}
const author=(actor:CoreActor)=>{if(!actor.startsWith('user:'))throw new CoreRuleError('bad_actor','Потрібне рішення автора.');};
const secretOf=(state:SecretVaultState,id:string)=>{const s=state.secrets.find(s=>s.id===id);if(!s)throw new CoreRuleError('not_found','Секрет не знайдено.');return s;};
function payload(key:Buffer,p:string,s:VaultSecret){const v=s.versions.at(-1)!;const data=decryptVault<SecretPayload>(key,p,s.id,v.version,v.cipher);const hash=createHash('sha256').update(JSON.stringify([p,s.id,v.version,data.salt,data.text,data.bounds,data.policy])).digest('hex');if(!timingSafeEqual(Buffer.from(hash),Buffer.from(v.commitment)))throw new CoreRuleError('conflict','Commitment Vault не збігається.');return data;}
async function append(repo:CoreRepository,p:string,state:SecretVaultState,s:VaultSecret,action:VaultAudit['action'],actor:string){const previousHash=state.audit.at(-1)?.hash??'',body={seq:state.audit.length+1,secretId:s.id,action,actor,at:new Date().toISOString(),previousHash,version:s.versions.at(-1)!.version};state.audit.push({...body,hash:createHash('sha256').update(JSON.stringify(body)).digest('hex')});const expected=state.revision;state.revision++;await repo.saveSecretVault(p,state,expected);return state;}
function addVersion(key:Buffer,p:string,s:VaultSecret,data:SecretPayload){const version=s.versions.length+1;data.salt=randomBytes(32).toString('base64');s.versions.push({version,commitment:createHash('sha256').update(JSON.stringify([p,s.id,version,data.salt,data.text,data.bounds,data.policy])).digest('hex'),cipher:encryptVault(key,p,s.id,version,data),createdAt:new Date().toISOString()});}
export function vaultMetadata(state:SecretVaultState){return {revision:state.revision,secrets:state.secrets.map(s=>({id:s.id,kind:s.kind,characterId:s.characterId,originSimulationId:s.originSimulationId,createdSceneId:s.createdSceneId,hiddenFromAuthor:s.hiddenFromAuthor,used:s.used,frozen:s.frozen,status:s.status,authorRevealed:!!s.authorRevealed,revealedSceneId:s.revealedSceneId,version:s.versions.at(-1)!.version,commitment:s.versions.at(-1)!.commitment,createdAt:s.createdAt})),audit:state.audit.map(e=>({...e})),notice:'Таємниці приховані від звичайного інтерфейсу автора. Адміністратор інфраструктури з доступом до ключа й бази технічно може їх прочитати. Приватні AI-виклики передають дані вибраному провайдеру.'};}
function rev(state:SecretVaultState,expected:unknown){if(!Number.isSafeInteger(expected)||expected!==state.revision)throw new CoreRuleError('conflict','Vault уже змінили. Оновіть стан.');}
async function policyFor(repo:CoreRepository,p:string,value:any,originScene:string):Promise<RevealPolicy>{const q=value??{},causal=parseCausalityPolicy({requiresKnowledge:q.requiredEventIds??[],claims:q.claims??[]});const allowed=q.allowedCharacterIds??[];if(!Array.isArray(allowed)||allowed.length>20||allowed.some(id=>typeof id!=='string'))throw new CoreRuleError('bad_input','Некоректні учасники розкриття.');for(const id of allowed){const e=await repo.getEntity(p,id);if(!e||e.type!=='character'||e.status!=='confirmed')throw new CoreRuleError('bad_input','Потрібні підтверджені герої.');}const policy={notBeforeSceneId:q.notBeforeSceneId??originScene,requiredEventIds:causal.requiresKnowledge,allowedCharacterIds:[...new Set<string>(allowed)],claims:causal.claims};if(typeof policy.notBeforeSceneId!=='string')throw new CoreRuleError('bad_input','Потрібна сцена найранішого розкриття.');await checkSecretReveal(repo,p,policy,policy.notBeforeSceneId);if(!await sceneAtOrAfter(repo,p,policy.notBeforeSceneId,originScene))throw new CoreRuleError('bad_input','Розкриття не може бути раніше створення секрету.');return policy;}
export async function createSecret(repo:CoreRepository,key:Buffer,p:string,input:any,actor:CoreActor,generate?:(context:Record<string,unknown>)=>Promise<unknown>){author(actor);checkedKey(key);const state=await repo.getSecretVault(p);rev(state,input.expectedRevision);if(!['personal_secret','false_belief','world_secret'].includes(input.kind)||typeof input.bounds!=='string'||!input.bounds.trim()||input.bounds.length>2000||typeof input.hiddenFromAuthor!=='boolean')throw new CoreRuleError('bad_input','Потрібні тип, межі й режим видимості.');const sim=await repo.getSimulation(p,input.simulationId),run=await repo.getMagicSceneRun(p,input.simulationId);if(!sim||!run||run.events.length||run.busy||sim.status!=='active')throw new CoreRuleError('conflict','Створення — тільки до першого ходу активного прогону.');const characterId=input.kind==='world_secret'?null:input.characterId;if(characterId&&!run.participants.includes(characterId)||input.kind!=='world_secret'&&!characterId)throw new CoreRuleError('bad_input','Секрет належить учаснику прогону.');const policy=await policyFor(repo,p,input.policy,sim.sceneId!);let text=input.text;
 if(input.hiddenFromAuthor||text===undefined){if(input.hiddenFromAuthor&&input.text!==undefined)throw new CoreRuleError('bad_input','Прихований від автора секрет створює лише куратор.');if(!generate)throw new CoreRuleError('conflict','Куратор секретів не підключений.');try{const out:any=await generate({kind:input.kind,bounds:input.bounds,character:characterId?{id:characterId,name:(await repo.getEntity(p,characterId))?.name}:null,policy});text=out?.text;}catch{throw new CoreRuleError('conflict','Куратор не створив секрет. Приватні дані не журналюються.');}}
 if(typeof text!=='string'||!text.trim()||text.length>2000)throw new CoreRuleError('bad_input','Секрет — непорожній текст до 2000 символів.');
 const current=await repo.getSecretVault(p);rev(current,state.revision);const live=await repo.getMagicSceneRun(p,input.simulationId);if(!live||live.events.length||live.busy)throw new CoreRuleError('conflict','Прогін уже почався.');const s:VaultSecret={id:randomUUID(),kind:input.kind,characterId,originSimulationId:sim.id,createdSceneId:sim.sceneId!,hiddenFromAuthor:input.hiddenFromAuthor,used:false,frozen:false,status:'sealed',versions:[],createdAt:new Date().toISOString()};addVersion(key,p,s,{text:text.trim(),bounds:input.bounds,salt:'',policy});current.secrets.push(s);await append(repo,p,current,s,'create',actor);return vaultMetadata(current);}
export async function secretControl(repo:CoreRepository,key:Buffer,p:string,id:string,input:any,actor:CoreActor,generate?:(context:Record<string,unknown>)=>Promise<unknown>){author(actor);checkedKey(key);const state=await repo.getSecretVault(p);rev(state,input.expectedRevision);const s=secretOf(state,id);
 if(input.action==='freeze'){if(s.status!=='sealed')throw new CoreRuleError('conflict','Заморожують лише закритий секрет.');s.frozen=true;await append(repo,p,state,s,'freeze',actor);return vaultMetadata(state);}
 if(input.action==='emergency_reveal'){if(input.confirm!==true)throw new CoreRuleError('bad_input','Потрібне явне аварійне розкриття автору.');const data=payload(key,p,s);s.authorRevealed=true;s.frozen=true;await append(repo,p,state,s,'emergency_reveal',actor);return {...vaultMetadata(state),emergency:{secretId:s.id,text:data.text,kind:s.kind,notice:'Прочитано автором; у світі історії секрет ще не розкрито.'}};}
 if(input.action==='regenerate'){if(s.used||s.frozen||s.status!=='sealed')throw new CoreRuleError('conflict','Зафіксований або використаний секрет не змінюється.');const run=await repo.getMagicSceneRun(p,s.originSimulationId);if(!run||run.events.length||run.busy)throw new CoreRuleError('conflict','Повторна генерація — лише до першого ходу.');const data=payload(key,p,s);let text=input.text;if(s.hiddenFromAuthor){if(input.text!==undefined||!generate)throw new CoreRuleError('bad_input','Прихований секрет повторно створює куратор.');try{text=(await generate({kind:s.kind,bounds:data.bounds,policy:data.policy}) as any)?.text;}catch{throw new CoreRuleError('conflict','Куратор не створив нову версію.');}}if(typeof text!=='string'||!text.trim()||text.length>2000)throw new CoreRuleError('bad_input','Нова версія — до 2000 символів.');const current=await repo.getSecretVault(p);rev(current,state.revision);const live=await repo.getMagicSceneRun(p,s.originSimulationId);if(!live||live.events.length||live.busy)throw new CoreRuleError('conflict','Прогін уже почався.');const target=secretOf(current,id);addVersion(key,p,target,{...data,text:text.trim(),director:undefined});await append(repo,p,current,target,'regenerate',actor);return vaultMetadata(current);}
 throw new CoreRuleError('bad_input','Невідома дія Vault.');}
export async function sceneAtOrAfter(repo:CoreRepository,p:string,scene:string,earliest:string){const scan=await scanScenes(repo,p,await repo.listTimePoints(p));const a=scan.bySection.get(earliest),b=scan.bySection.get(scene);return !!a&&!!b&&(a.sectionId===b.sectionId||sceneIsBefore(a,b));}
export async function readCharacterSecret(repo:CoreRepository,key:Buffer,scope:Readonly<BookToolScope>,id:string){const state=await repo.getSecretVault(scope.projectId),s=secretOf(state,id),sim=await repo.getSimulation(scope.projectId,scope.simulationId),run=await repo.getMagicSceneRun(scope.projectId,scope.simulationId);if(!sim||sim.sceneId!==scope.sceneId||!run?.participants.includes(scope.characterId)||s.status==='archived'||!await sceneAtOrAfter(repo,scope.projectId,scope.sceneId,s.createdSceneId))throw new CoreRuleError('bad_actor','Секрет недоступний цьому герою й сцені.');const data=payload(key,scope.projectId,s);const own=s.kind!=='world_secret'&&s.characterId===scope.characterId;const disclosed=s.status==='revealed'&&data.policy.allowedCharacterIds.includes(scope.characterId)&&!!s.revealedSceneId&&await sceneAtOrAfter(repo,scope.projectId,scope.sceneId,s.revealedSceneId);if(!own&&!disclosed)throw new CoreRuleError('bad_actor','Секрет недоступний цьому герою.');if(!s.used){s.used=true;await append(repo,scope.projectId,state,s,'first_use',scope.actorId);}return {secretId:s.id,kind:s.kind,content:data.text,layer:s.kind==='false_belief'?'character_belief':'private_knowledge',truth:s.kind==='false_belief'?'false':'unknown'};}
export async function characterSecretIds(repo:CoreRepository,key:()=>Buffer,p:string,characterId:string,sceneId:string){const state=await repo.getSecretVault(p),ids:string[]=[];for(const s of state.secrets){if(s.status==='archived'||!await sceneAtOrAfter(repo,p,sceneId,s.createdSceneId))continue;if(s.characterId===characterId){ids.push(s.id);continue;}if(s.status==='revealed'&&s.revealedSceneId&&await sceneAtOrAfter(repo,p,sceneId,s.revealedSceneId)&&payload(key(),p,s).policy.allowedCharacterIds.includes(characterId))ids.push(s.id);}return ids;}
export async function directMystery(repo:CoreRepository,key:Buffer,p:string,id:string,input:any,actor:CoreActor,direct?:(context:Record<string,unknown>)=>Promise<unknown>){author(actor);const state=await repo.getSecretVault(p);rev(state,input.expectedRevision);const s=secretOf(state,id);if(s.kind!=='world_secret'||s.status!=='sealed')throw new CoreRuleError('bad_input','Mystery Director працює лише з потрібною закритою світовою таємницею.');const data=payload(key,p,s);
 if(!await sceneAtOrAfter(repo,p,input.sceneId,s.createdSceneId))throw new CoreRuleError('bad_input','Планування не може бути раніше створення таємниці.');
 const checks=await checkSecretReveal(repo,p,data.policy,input.sceneId),knowledge=await mysteryKnowledge(repo,p,input.sceneId);
 if(!s.used){s.used=true;await append(repo,p,state,s,'first_use',actor);}
 let result:any={hints:[]};if(direct){try{result=await direct({secret:{id:s.id,text:data.text,bounds:data.bounds},worldTruth:{secretId:s.id,text:data.text,source:'sealed_world_secret'},mysteryState:{status:s.status,policy:data.policy,checks},policy:data.policy,checks,...knowledge.context});if(!Array.isArray(result?.hints)||result.hints.length>5||result.hints.some((x:any)=>typeof x!=='string'||x.length>1000))throw new Error();}catch(error){rethrowMysteryInterruption(error);throw new CoreRuleError('conflict','Mystery Director не сформував перевірений план. Приватні дані не журналюються.');}}
 const recommendation=mysteryRecommendation(result,checks.allowed);
 const freshKnowledge=await mysteryKnowledge(repo,p,input.sceneId),freshChecks=await checkSecretReveal(repo,p,data.policy,input.sceneId);
 if(freshKnowledge.fingerprint!==knowledge.fingerprint||JSON.stringify(freshChecks)!==JSON.stringify(checks))throw new CoreRuleError('conflict','Знання або умови загадки змінилися. Повторіть аналіз.');
 // Never put the private context or free-form provider result into run traces.
 const attachment=encryptVault(key,p,s.id,s.versions.at(-1)!.version,{hints:result.hints,evidenceIds:data.policy.requiredEventIds,recommendation,knowledgeFingerprint:knowledge.fingerprint});
 const current=await repo.getSecretVault(p);rev(current,state.revision);const target=secretOf(current,id);target.used=true;current.plans=[...(current.plans??[]),{secretId:s.id,cipher:attachment}];await append(repo,p,current,target,'director',actor);
 return {...vaultMetadata(current),director:{secretId:s.id,hintCount:result.hints.length,checks,...recommendation,layers:{worldTruth:'sealed',readerParagraphs:knowledge.context.readerKnowledge.paragraphs.length,characters:knowledge.context.characterKnowledge.characters.map(c=>({characterId:c.characterId,knownCount:c.known.length,worldSecretDisclosed:false}))},notice:'Лише рекомендація. Знання — на початок сцени. Розкриття підтверджує автор окремо.'}};}

export async function revealSecret(repo:CoreRepository,key:Buffer,p:string,id:string,input:any,actor:CoreActor){author(actor);const state=await repo.getSecretVault(p);rev(state,input.expectedRevision);const s=secretOf(state,id);if(input.confirm!==true)throw new CoreRuleError('bad_input','Явно підтвердьте розкриття в історії.');if(s.status!=='sealed')throw new CoreRuleError('conflict','Секрет уже розкрито або архівовано.');const data=payload(key,p,s),checks=await checkSecretReveal(repo,p,data.policy,input.sceneId);if(!checks.allowed)throw new CoreRuleError('conflict','Умови причинності для розкриття ще не виконані.');s.used=true;s.frozen=true;s.status='revealed';s.revealedSceneId=input.sceneId;await append(repo,p,state,s,'reveal',actor);return {...vaultMetadata(state),revelation:{secretId:s.id,sectionId:input.sceneId,text:s.kind==='false_belief'?`Хибне переконання героя: ${data.text}`:data.text,tag:`[/revelation:Розкриття ${s.id}]`,status:'proposal',layer:s.kind==='false_belief'?'character_belief':'disclosed_knowledge',checks}};}
export async function archiveSecretSimulation(repo:CoreRepository,key:Buffer,p:string,simulationId:string,input:any,actor:CoreActor){author(actor);checkedKey(key);if(input.confirm!==true)throw new CoreRuleError('bad_input','Явно підтвердьте архівування прогону.');const state=await repo.getSecretVault(p);rev(state,input.expectedRevision);const run=await repo.getMagicSceneRun(p,simulationId);if(!run||run.busy)throw new CoreRuleError('conflict','Дочекайтеся завершення дії прогону.');const targets=state.secrets.filter(s=>s.originSimulationId===simulationId&&s.status==='sealed');for(const s of targets){const fresh=await repo.getSecretVault(p),target=secretOf(fresh,s.id);target.status='archived';target.frozen=true;await append(repo,p,fresh,target,'archive',actor);}run.status='closed';run.revision++;await repo.saveMagicSceneRun(p,run,run.revision-1);await repo.updateSimulation(p,simulationId,{status:'closed'});return vaultMetadata(await repo.getSecretVault(p));}

export async function revelationBranch(repo:CoreRepository,key:Buffer,p:string,id:string,input:any,actor:CoreActor){author(actor);const state=await repo.getSecretVault(p);rev(state,input.expectedRevision);const s=secretOf(state,id);if(s.status!=='revealed'||!s.revealedSceneId)throw new CoreRuleError('conflict','Спершу автор підтверджує розкриття в історії.');const data=payload(key,p,s);const {createBranch}=await import('./branches');const branches=await repo.getBranchWorkspace(p);const existing=branches.branches.find(b=>b.sourceId===`vault:${id}`);if(existing)return {branch:existing};if(!Number.isSafeInteger(input.expectedBranchRevision)||input.expectedBranchRevision!==branches.revision)throw new CoreRuleError('conflict','Гілки вже змінили.');const stored=await getBook(p);if(!stored)throw new CoreRuleError('not_found','Книгу не знайдено.');return createBranch(repo,p,stored,{name:'Розкриття таємниці',source:'author',sourceId:`vault:${id}`,expectedRevision:branches.revision,initialFragment:{sectionId:s.revealedSceneId,text:`${s.kind==='false_belief'?'Хибне переконання героя: ':''}${cleanFragmentText(data.text)} [/revelation:Розкриття ${s.id}]`}},actor);}
