import type { LabyrinthDefinition } from "./labyrinth";
/** Small author-preview fixture for T9.1; not a published game or manuscript. */
export const labyrinthDemo: LabyrinthDefinition = {
  schemaVersion: 1,
  title: "Лабіринт над коридором",
  startNodeId: "lower-entry",
  exitNodeIds: ["lower-exit"],
  nodes: [
    {
      id: "lower-entry",
      title: "Вхід",
      level: "lower",
      x: 0,
      y: 0,
      sceneId: null,
      description: "Під мостом",
      cover: true,
    },
    {
      id: "lower-exit",
      title: "Вихід",
      level: "lower",
      x: 2,
      y: 0,
      sceneId: null,
      description: "Нижній коридор",
      cover: false,
    },
    {
      id: "upper-left",
      title: "Лівий край мосту",
      level: "upper",
      x: 0,
      y: 0,
      sceneId: null,
      description: "Над входом",
      cover: false,
    },
    {
      id: "upper-right",
      title: "Правий край мосту",
      level: "upper",
      x: 2,
      y: 0,
      sceneId: null,
      description: "Над виходом",
      cover: false,
    },
    {
      id: "isolated-room",
      title: "Інша кімната",
      level: "lower",
      x: 3,
      y: 2,
      sceneId: null,
      description: "Не пов’язана з мостом",
      cover: true,
    },
  ],
  edges: [
    {
      id: "corridor",
      from: "lower-entry",
      to: "lower-exit",
      kind: "corridor",
      bidirectional: true,
      duration: 2,
      costs: { energy: 2 },
      conditions: [],
      overNodeIds: [],
    },
    {
      id: "up",
      from: "lower-entry",
      to: "upper-left",
      kind: "ladder",
      bidirectional: true,
      duration: 1,
      costs: { energy: 1 },
      conditions: [],
      overNodeIds: [],
    },
    {
      id: "bridge",
      from: "upper-left",
      to: "upper-right",
      kind: "bridge",
      bidirectional: true,
      duration: 1,
      costs: { energy: 1 },
      conditions: [{ objectId: "bridge-gate", state: "open" }],
      overNodeIds: ["lower-entry", "lower-exit"],
    },
    {
      id: "down",
      from: "upper-right",
      to: "lower-exit",
      kind: "stairs",
      bidirectional: true,
      duration: 1,
      costs: {},
      conditions: [],
      overNodeIds: [],
    },
  ],
  objects: [
    {
      id: "bridge-gate",
      nodeId: "upper-right",
      entityId: null,
      kind: "gate",
      states: ["open", "closed"],
      initialState: "open",
      transitions: [],
    },
    {
      id: "generator",
      nodeId: "lower-entry",
      entityId: null,
      kind: "generator",
      states: ["on", "off"],
      initialState: "on",
      transitions: [
        {
          from: "on",
          to: "off",
          conditions: [],
          effects: [{ objectId: "bridge-gate", state: "closed" }],
        },
        {
          from: "off",
          to: "on",
          conditions: [],
          effects: [{ objectId: "bridge-gate", state: "open" }],
        },
      ],
    },
    {
      id: "other-door",
      nodeId: "isolated-room",
      entityId: null,
      kind: "door",
      states: ["open", "closed"],
      initialState: "closed",
      transitions: [],
    },
  ],
  heroes: [
    {
      id: "hero",
      entityId: null,
      name: "Мандрівник",
      startNodeId: "lower-entry",
      resources: { health: 100, energy: 10 },
      inventory: ["Ліхтар"],
      goals: ["Знайти вихід"],
      fears: ["Темрява"],
      knowledge: ["Вхід під мостом"],
    },
  ],
  events: [
    {
      id: "gas-warning",
      nodeIds: ["lower-entry"],
      conditions: [{ objectId: "generator", state: "off" }],
      warning: "У коридорі чути шипіння.",
      preparation: 2,
      duration: 3,
      cooldown: 5,
      effects: [],
      avoidance: "Піднятися драбиною",
    },
  ],
};
