/** Non-destructive T4.3 browser probe: unique project + temporary SQLite, no DROP SCHEMA. */
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {randomUUID,randomBytes} from 'node:crypto';import {spawn} from 'node:child_process';import assert from 'node:assert/strict';
import {initialBook} from '../src/data/initialBook';
import {CORE_PAGES} from '../src/utils/appRoutes';
const db=process.env.CORE_TEST_DATABASE_URL;if(!db)throw new Error('Set CORE_TEST_DATABASE_URL to a dedicated local test database.');
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'t43-'));process.env.DATA_DIR=dir;process.env.DATABASE_PATH=path.join(dir,'test.db');
const user='accept-'+randomUUID(),id='BK-accept-'+randomUUID(),token=randomBytes(24).toString('hex');
const {initStore,saveUser,createSession}=await import('../server/store');await initStore();await saveUser({id:user,email:user+'@test.invalid',name:'Приймання',role:'admin',createdAt:new Date().toISOString()} as any);await createSession({token,userId:user,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString()});
const {saveBook}=await import('../server/bookStore');const stored=await saveBook({ownerId:user,book:{...structuredClone(initialBook),id,title:'Приймання Т4.3',characters:[],illustrations:[],chapters:[{id:'ch',title:'Глава',order:0,sections:[{id:'scene',title:'Сцена',order:0,content:'[/character:Олена] Олена тримає лист. [/emotion:тривога @Олена]'}]}]} as any});
const {createCorePool}=await import('../server/core');const {PgCoreRepository}=await import('../server/core/pgRepository');const {runMigrations,loadMigrations,resolveMigrationsDir}=await import('../server/core/migrate');const {syncBookToCore}=await import('../server/core/sync');const pool=createCorePool(db);await runMigrations(pool,loadMigrations(resolveMigrationsDir()));const repo=new PgCoreRepository(pool);await syncBookToCore(repo,stored);
const port=45113,origin=`http://localhost:${port}`;const child=spawn(process.execPath,['dist/server.mjs'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),NODE_ENV:'production',CORE_DATABASE_URL:db,ROLE_ONBOARDING:'off'},stdio:['ignore','ignore','ignore']});let browser:any;let failures=0;const results:any[]=[];console.log('Project ready');const artifact='/tmp/t43-browser';await fs.mkdir(artifact,{recursive:true});
try{
 for(let i=0;i<100;i++){try{const health=await(await fetch(origin+'/api/health')).json();if(health.core==='ready')break;}catch{}await new Promise(r=>setTimeout(r,300));if(i===99)throw new Error('Server not ready');}
 const puppeteer=await import('puppeteer-core');browser=await puppeteer.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});await browser.setCookie({name:'nova_session',value:token,domain:'localhost',path:'/'});
 const {build}=await import('esbuild');const bundle=await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import{CorePageView}from'./src/components/CorePageView';import{LanguageProvider}from'./src/i18n/LanguageContext';import{CORE_PAGES}from'./src/utils/appRoutes';const definition=CORE_PAGES.find(p=>location.pathname.endsWith('/'+p.segment));createRoot(document.getElementById('root')).render(React.createElement(LanguageProvider,null,React.createElement(CorePageView,{tab:definition.tab,book:${JSON.stringify(stored.book)},authUser:{id:${JSON.stringify(user)},role:'admin'},onOpenCharacter:()=>{},onOpenParagraph:()=>{}})));`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,outfile:'/tmp/t43-probe.js',format:'iife',platform:'browser',define:{'import.meta.env':'{"DEV":false,"PROD":true}'},logLevel:'error'});
 const page=await browser.newPage();await page.setRequestInterception(true);page.on('request',request=>{if(new URL(request.url()).pathname==='/favicon.ico'){void request.respond({status:204,body:''});return;}if(request.resourceType()==='script'&&/\/assets\/index-[^/]+\.js/.test(request.url()))void request.respond({status:200,contentType:'application/javascript',body:bundle.outputFiles.find(file=>file.path.endsWith('.js'))!.text});else void request.continue();});
 console.log('Isolated CorePageView with real API ready');
 const errors:string[]=[];page.on('pageerror',(error:Error)=>errors.push(error.message));page.on('console',(message:any)=>{if(message.type()==='error')errors.push(message.text());});page.on('dialog',async(dialog:any)=>dialog.accept());
 for(const width of [390,1440])for(const theme of ['dark','light'])for(const def of CORE_PAGES){
  errors.length=0;await page.setViewport({width,height:900});await page.evaluateOnNewDocument((theme:string)=>{localStorage.setItem('nova_theme',theme);if(document.documentElement)document.documentElement.dataset.theme=theme;},theme);
  await page.goto(origin+`/projects/${id}/${def.segment}`,{waitUntil:'domcontentloaded'});const css=bundle.outputFiles.find(file=>file.path.endsWith('.css'));if(css)await page.addStyleTag({content:css.text});
  try{await page.waitForSelector(def.tab==='core-visual'?'[data-media-mode]':`[data-core-page="${def.segment}"]`,{timeout:25000});await page.waitForNetworkIdle({idleTime:200,timeout:10000}).catch(()=>{});await page.evaluate((theme:string)=>document.documentElement.dataset.theme=theme,theme);
   const state=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,theme:document.documentElement.dataset.theme,heading:document.querySelector('[data-core-page] h1')?.textContent,background:getComputedStyle((document.querySelector('[data-core-page]')??document.querySelector('#root > *'))!).backgroundColor,problem:document.querySelector('[data-core-problem]')?.textContent}));
   const passed=state.scrollWidth<=state.width&&errors.filter(e=>!e.includes('ERR_TUNNEL_CONNECTION_FAILED')).length===0&&!state.problem;results.push({page:def.segment,width,theme,passed,...state,errors:[...errors]});if(!passed)failures++;await page.screenshot({path:path.join(artifact,`${def.segment}-${width}-${theme}.png`),fullPage:true});console.log(`${passed?'✓':'✗'} ${def.segment} ${width} ${theme}: ${state.scrollWidth}px ${errors.join(' | ')}`);
  }catch(error){failures++;results.push({page:def.segment,width,theme,passed:false,error:String(error)});console.log(`✗ ${def.segment} ${width} ${theme}: ${error}; ${errors.join(' | ')}`);await page.screenshot({path:path.join(artifact,'failed.png')});throw error;}
 }
 await fs.writeFile(path.join(artifact,'report.json'),JSON.stringify({mode:'isolated CorePageView with real PostgreSQL API; full App blocked by Firebase configuration',at:new Date().toISOString(),results,failures},null,2));assert.equal(failures,0,`${failures} browser acceptance failures; ${artifact}/report.json`);console.log(`44 сторінки/розміри/теми перевірено.`);
}finally{await fs.writeFile(path.join(artifact,'report.json'),JSON.stringify({mode:'isolated CorePageView with real PostgreSQL API; full App blocked by Firebase configuration',at:new Date().toISOString(),results,failures},null,2));await browser?.close();child.kill('SIGTERM');await new Promise<void>(r=>{if(child.exitCode!==null)r();else child.once('exit',()=>r());});await pool.query('DELETE FROM fusion_core.projects WHERE id=$1',[id]);await pool.end();await fs.rm(dir,{recursive:true,force:true});}
