import assert from 'node:assert/strict';import express from 'express';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {randomUUID,randomBytes} from 'node:crypto';import type {AddressInfo} from 'node:net';
import type {CoreRepository} from '../server/core/types';import {MemoryCoreRepository} from '../server/core/memoryRepository';import {PgCoreRepository} from '../server/core/pgRepository';import {createCorePool} from '../server/core';import {loadMigrations,resolveMigrationsDir,runMigrations} from '../server/core/migrate';
import {registerSecretVaultRoutes} from '../server/core/secretVaultRoutes';import {registerMagicSceneRoutes} from '../server/core/magicSceneRoutes';import {registerProjectRoutes} from '../server/core/projectRoutes';import {startMagic,stepMagic} from '../server/core/magicScene';import {createBookToolRuntime} from '../server/ai/tools';import {decryptVault,encryptVault,readCharacterSecret,vaultKeyFromEnv,VaultUnavailableError,secretControl} from '../server/core/secretVault';import {branchHash,branchCanonHash,mergeBranchFragment} from '../server/core/branches';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'vault-'));process.env.DATA_DIR=dir;process.env.DATABASE_PATH=path.join(dir,'test.db');const {saveBook,getBook}=await import('../server/bookStore');const {syncBookToCore}=await import('../server/core/sync');
async function suite(repo:CoreRepository){let n=0;const check=async(label:string,fn:()=>any)=>{await fn();n++;console.log('✓ '+label);};const key=randomBytes(32),p='vault-'+randomUUID(),actor='user:owner' as const;
 const stored=await saveBook({ownerId:'owner',book:{id:p,title:'Vault test',chapters:[{id:'ch',sections:[{id:'past',title:'Минуле',content:'[/event:Доказ] Герой знайшов лист.'},{id:'scene',title:'Початок',content:'Герої зустрілися.'},{id:'next',title:'Розкриття',content:'Вони знову зустрілися.'},{id:'future',title:'Майбутнє',content:'[/event:Пізній доказ] Пізня подія.'}]}]} as any});await syncBookToCore(repo,stored);
 const heroes=[];for(const name of ['Олена','Марко']){const h=await repo.createEntity({projectId:p,type:'character',name,status:'confirmed',createdBy:actor});heroes.push(h);await repo.upsertCharacterAgent({projectId:p,characterId:h.id,autonomyLevel:'scene',actor,agentConfig:{}});}const [h1,h2]=heroes;
 const evidence=await repo.resolveAlias(p,'event','Доказ'),futureEvidence=await repo.resolveAlias(p,'event','Пізній доказ');assert.ok(evidence&&futureEvidence);
 const begin=()=>startMagic(repo,p,'scene',{participants:heroes.map(h=>h.id),goal:'Зустріч '+randomUUID(),constraints:'Не розкривати секрет',maxTurns:6},actor);const first=await begin();
 const privateContexts:any[]=[],publicContexts:any[]=[],directorContexts:any[]=[];let curatorCount=0,curatorBad=false,privateBad=false;
 const canaries=['СЕКРЕТ_ОЛЕНИ_7bd','ХИБНЕ_ПЕРЕКОНАННЯ_7bd','СВІТОВА_ТАЄМНИЦЯ_7bd'];const secretText=(kind:string)=>canaries[['personal_secret','false_belief','world_secret'].indexOf(kind)];
 const engines={vaultKey:()=>key,decide:async()=>({action:'answer',source:'fixture'}),secretChoice:async(c:any)=>{privateContexts.push(c);if(privateBad)throw new Error(canaries[0]);return {action:'silence',leak:canaries.join(' ')};},voice:async(c:any)=>{publicContexts.push(c);return {speech:'Герой обережно відповів.',actionText:'Відводить очі.',privateThought:'Обмірковує відповідь.',intent:'Бути обережним.'};},writer:async(c:any)=>{publicContexts.push(c);return {fragments:[{text:'Герої обмінялися обережними словами.',eventIds:c.events.map((e:any)=>e.id)}]};}};
 const access={getBookOwnerId:async()=> 'owner',getCollabOwnerId:async()=>undefined,listAcceptedInvites:async()=>[{acceptedUserId:'reader',role:'reader' as const}]};
 const app=express();app.use(express.json());app.use((req,_res,next)=>{const id=String(req.headers['x-user']??'owner');req.principal={id:id==='guest'?null:id,isGuest:id==='guest',role:'writer'} as any;next();});registerProjectRoutes(app,{repo:()=>repo,access,coreState:()=> 'ready'});registerMagicSceneRoutes(app,{repo:()=>repo,access,engines:async()=>engines});registerSecretVaultRoutes(app,{repo:()=>repo,access,key:()=>key,generate:async(_req,_p,c:any)=>{curatorCount++;if(curatorBad)throw new Error(canaries.join(' '));return {text:secretText(c.kind)+(curatorCount>3?'_нова':'')};},direct:async(_req,_p,c)=>{directorContexts.push(c);return {hints:['Зашифрований натяк '+canaries[2]]};}});
 const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const origin=`http://127.0.0.1:${(server.address() as AddressInfo).port}`,base=`/api/core/projects/${p}`;
 const req=async(url:string,method='GET',body?:any,user='owner')=>{const r=await fetch(origin+url,{method,headers:{'Content-Type':'application/json','x-user':user},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json(),cache:r.headers.get('cache-control')};};const meta=async()=> (await req(base+'/vault')).body;const mutate=async(url:string,body:any)=>req(base+'/vault'+url,'POST',{...body,expectedRevision:(await meta()).revision});const hash=async()=>branchHash({book:(await getBook(p))!.book,canon:await branchCanonHash(repo,p),memories:await repo.listCharacterMemories(p,{limit:1000}),findings:await repo.listFindings(p)});const before=await hash();
 try{
 for(const user of ['guest','stranger','reader'])await check('Vault недоступний '+user,async()=>assert.equal((await req(base+'/vault','GET',undefined,user)).status,user==='guest'?401:403));
 await check('ключ Vault не створюється автоматично',()=>{const old=process.env.SECRET_VAULT_KEY_BASE64;delete process.env.SECRET_VAULT_KEY_BASE64;assert.throws(vaultKeyFromEnv,VaultUnavailableError);if(old!==undefined)process.env.SECRET_VAULT_KEY_BASE64=old;});
 const ids:string[]=[];for(const kind of ['personal_secret','false_belief','world_secret']){const created=await mutate('',{kind,simulationId:first.simulationId,characterId:kind==='world_secret'?null:h1.id,hiddenFromAuthor:true,bounds:'Без насильства. Український детектив.',policy:{notBeforeSceneId:'next',requiredEventIds:[evidence],allowedCharacterIds:heroes.map(h=>h.id)}});assert.equal(created.status,200,JSON.stringify(created.body));ids.push(created.body.secrets.at(-1).id);}
 await check('створено три типи без зміни канону чи рукопису',async()=>{assert.equal((await meta()).secrets.length,3);assert.equal(await hash(),before);});
 const initial=await repo.getSecretVault(p);await check('у базі лише ciphertext, salt не відкритий',()=>{for(const code of canaries)assert.ok(!JSON.stringify(initial).includes(code));assert.ok(!JSON.stringify(initial).includes('Без насильства'));});
 await check('AES-GCM відкидає інший ключ, проєкт і підміну ciphertext',()=>{const version=initial.secrets[0].versions[0];assert.throws(()=>decryptVault(randomBytes(32),p,ids[0],1,version.cipher));assert.throws(()=>decryptVault(key,'other',ids[0],1,version.cipher));assert.throws(()=>decryptVault(key,p,ids[0],1,{...version.cipher,tag:randomBytes(16).toString('base64')}));});
 await check('IV та commitment різні для однакового тексту',()=>{const a=encryptVault(key,p,'same',1,{text:canaries[0]}),b=encryptVault(key,p,'same',1,{text:canaries[0]});assert.notEqual(a.iv,b.iv);assert.notEqual(a.data,b.data);});
 const regenerated=await mutate('/'+ids[0]+'/control',{action:'regenerate'});await check('повторна генерація до використання зберігає попередню версію',async()=>{assert.equal(regenerated.status,200);const s=(await repo.getSecretVault(p)).secrets[0];assert.equal(s.versions.length,2);assert.deepEqual(s.versions[0],initial.secrets[0].versions[0]);assert.notEqual(s.versions[0].commitment,s.versions[1].commitment);});
 const scope={projectId:p,actorId:actor,characterId:h1.id,sceneId:'scene',simulationId:first.simulationId};const runtime=createBookToolRuntime({repo,scope,authorize:async()=>true,allowedActions:['answer'],situation:'Лист',vaultKey:()=>key});
 const call=(id:string)=>runtime.step('character-agent',['read-authorized-secret'],ctx=>ctx.tool<any>('read-authorized-secret',{secretId:id}));
 const own=await call(ids[0]);await check('власник героя отримує лише свій особистий секрет',()=>assert.ok(own.content.includes(canaries[0])));
 await check('світова таємниця недоступна Character Agent',()=>assert.rejects(()=>call(ids[2])));
 const foreign={...scope,characterId:h2.id};await check('інший герой не читає чужого секрету',()=>assert.rejects(()=>readCharacterSecret(repo,key,foreign,ids[0])));
 const belief=await call(ids[1]);await check('хибне переконання не є world_truth',()=>{assert.equal(belief.layer,'character_belief');assert.equal(belief.truth,'false');});
 const used=(await repo.getSecretVault(p)).secrets[0];const noRegen=await mutate('/'+ids[0]+'/control',{action:'regenerate'});await check('використаний секрет незмінний',async()=>{assert.equal(noRegen.status,409);assert.deepEqual((await repo.getSecretVault(p)).secrets[0].versions,used.versions);});
 let run=await repo.getMagicSceneRun(p,first.simulationId);const step=await req(base+`/simulations/${first.simulationId}/step`,'POST',{expectedRevision:run!.revision,requestId:randomUUID()});await check('приватний вибір застосовує тільки дозволену дію',()=>{assert.equal(step.status,200,JSON.stringify(step.body));assert.equal(step.body.run.events[0].action,'silence');});
 await check('приватний агент не отримав світову таємницю чи чужі секрети',()=>{const text=JSON.stringify(privateContexts[0]);assert.ok(text.includes(canaries[0]));assert.ok(text.includes(canaries[1]));assert.ok(!text.includes(canaries[2]));});
 const second=await req(base+`/simulations/${first.simulationId}/step`,'POST',{expectedRevision:step.body.run.revision,requestId:randomUUID()});assert.equal(second.status,200);await check('другий герой не отримав приватний prompt першого',()=>assert.equal(privateContexts.length,1));
 const draft=await req(base+`/simulations/${first.simulationId}/draft`,'POST',{expectedRevision:second.body.run.revision});assert.equal(draft.status,200);await check('голос і літературний автор не бачать секретів',()=>{for(const code of canaries)assert.ok(!JSON.stringify(publicContexts).includes(code));});
 const publicUrls=[base+'/vault',base+'/magic-scenes',base+`/simulations/${first.simulationId}/events`,`/api/projects/${p}/search?q=${encodeURIComponent('СЕКРЕТ')}`,`/api/projects/${p}/story-graph`,`/api/projects/${p}/characters/${h1.id}/profile`,`/api/projects/${p}/characters/${h1.id}/memories`];
 for(const url of publicUrls)await check('немає витоку: '+url.split('/').slice(-1)[0],async()=>{const result=await req(url);assert.equal(result.status,200,JSON.stringify(result.body));for(const code of canaries)assert.ok(!JSON.stringify(result.body).includes(code));});
 await check('читання, хибне переконання й чернетка не змінили канон',async()=>assert.equal(await hash(),before));
 const direct=await mutate('/'+ids[2]+'/director',{sceneId:'scene'});await check('Mystery Director має лише потрібну світову таємницю',()=>{assert.equal(direct.status,200,JSON.stringify(direct.body));const text=JSON.stringify(directorContexts[0]);assert.ok(text.includes(canaries[2]));assert.ok(!text.includes(canaries[0]));assert.ok(!text.includes(canaries[1]));assert.equal(direct.body.director.checks.allowed,false);for(const code of canaries)assert.ok(!JSON.stringify(direct.body).includes(code));});
 await check('план натяків лишається зашифрованим',async()=>assert.ok(!JSON.stringify(await repo.getSecretVault(p)).includes(canaries[2])));
 const early=await mutate('/'+ids[2]+'/reveal',{sceneId:'scene',confirm:true});await check('CausalityService блокує раннє розкриття',()=>assert.equal(early.status,409));
 const noConfirm=await mutate('/'+ids[0]+'/control',{action:'emergency_reveal'});await check('аварійне читання потребує підтвердження',()=>assert.equal(noConfirm.status,400));
 const emergency=await mutate('/'+ids[0]+'/control',{action:'emergency_reveal',confirm:true});await check('аварійне читання автору не є розкриттям у світі',()=>{assert.equal(emergency.status,200);assert.ok(emergency.body.emergency.text.includes(canaries[0]));assert.equal(emergency.body.secrets[0].status,'sealed');assert.equal(emergency.cache,'no-store');});
 await check('після аварійного читання звичайний GET усе ще приховує текст',async()=>{for(const code of canaries)assert.ok(!JSON.stringify(await meta()).includes(code));});
 const futureRun=await begin();const missing=await mutate('',{kind:'world_secret',simulationId:futureRun.simulationId,hiddenFromAuthor:true,bounds:'Без змін канону.',policy:{notBeforeSceneId:'scene',requiredEventIds:[futureEvidence],allowedCharacterIds:[h1.id]}});assert.equal(missing.status,200);const missingId=missing.body.secrets.at(-1).id;
 await check('пізніший доказ не дозволяє раннє розкриття',async()=>assert.equal((await mutate('/'+missingId+'/reveal',{sceneId:'scene',confirm:true})).status,409));
 const frozen=await mutate('/'+missingId+'/control',{action:'freeze'});assert.equal(frozen.status,200);await check('Freeze забороняє нову версію невикористаного секрету',async()=>assert.equal((await mutate('/'+missingId+'/control',{action:'regenerate'})).status,409));
 const failingRun=await begin();curatorBad=true;const failed=await mutate('',{kind:'personal_secret',characterId:h1.id,simulationId:failingRun.simulationId,hiddenFromAuthor:true,bounds:'Межі.'});curatorBad=false;await check('помилка куратора не розкриває приватний текст',()=>{assert.equal(failed.status,409);for(const code of canaries)assert.ok(!JSON.stringify(failed).includes(code));});
 privateBad=true;const failedStep=await stepMagic({...engines,repo},p,failingRun.simulationId,{expectedRevision:failingRun.revision,requestId:randomUUID()},actor).then(()=>null,e=>e);privateBad=false;await check('помилка приватного кроку не витікає у lastError',async()=>{assert.ok(failedStep);for(const code of canaries)assert.ok(!JSON.stringify(await repo.getMagicSceneRun(p,failingRun.simulationId)).includes(code));});
 const decision=await repo.addCharacterDecision({projectId:p,characterId:h1.id,level:'tactical',sceneId:'scene',simulationId:failingRun.simulationId,cacheKey:randomUUID(),snapshotHash:randomBytes(32).toString('hex'),modelVersion:'fixture',source:'mock',createdBy:actor,selectedAction:'answer',options:{primary:{allowed:['answer'],forbidden:['silence']}}});
 const guarded=await repo.getMagicSceneRun(p,failingRun.simulationId);
 await check('приватний вибір не обходить жорсткі обмеження Jev',async()=>{await assert.rejects(()=>stepMagic({...engines,repo,decide:async()=>({action:'answer',source:'mock',decisionId:decision.id})},p,failingRun.simulationId,{expectedRevision:guarded!.revision,requestId:randomUUID()},actor));assert.equal((await repo.getMagicSceneRun(p,failingRun.simulationId))!.events.length,0);});
 await check('новий секрет не створюється після першого ходу',async()=>assert.equal((await mutate('',{kind:'world_secret',simulationId:first.simulationId,hiddenFromAuthor:true,bounds:'Нові межі.'})).status,409));
 const expected=(await meta()).revision;
 await check('CAS захищає одночасні дії Vault',async()=>{const results=await Promise.all([req(base+'/vault/'+ids[1]+'/control','POST',{action:'freeze',expectedRevision:expected}),req(base+'/vault/'+ids[1]+'/control','POST',{action:'freeze',expectedRevision:expected})]);assert.deepEqual(results.map(x=>x.status).sort(),[200,409]);});
 const revealed=await mutate('/'+ids[2]+'/reveal',{sceneId:'next',confirm:true});await check('після перевіреного розкриття є лише пропозиція П8',async()=>{assert.equal(revealed.status,200,JSON.stringify(revealed.body));assert.equal(revealed.body.revelation.status,'proposal');assert.ok(revealed.body.revelation.tag.startsWith('[/revelation:'));assert.equal(await hash(),before);});
 await check('розкриття не дає знання попередній сцені',()=>assert.rejects(()=>readCharacterSecret(repo,key,scope,ids[2])));
 const nextRun=await startMagic(repo,p,'next',{participants:heroes.map(h=>h.id),goal:'Наступна сцена',constraints:'Межі',maxTurns:2},actor);const disclosed=await readCharacterSecret(repo,key,{...foreign,sceneId:'next',simulationId:nextRun.simulationId},ids[2]);await check('дозволений герой знає розкриття у наступній сцені',()=>assert.equal(disclosed.content,canaries[2]));
 const branches=await repo.getBranchWorkspace(p);const branch=await mutate('/'+ids[2]+'/branch',{expectedBranchRevision:branches.revision});await check('пропозиція /revelation у гілці не змінює рукопис',async()=>{assert.equal(branch.status,200,JSON.stringify(branch.body));assert.equal(await hash(),before);});
 const fake=await repo.getSecretVault(p),original=structuredClone(fake);fake.audit[0].actor='user:other';fake.revision++;await check('сховище відкидає переписування журналу',()=>assert.rejects(()=>repo.saveSecretVault(p,fake,original.revision)));
 const altered=structuredClone(original);altered.secrets[0].versions[0].cipher.data='tamper';altered.revision++;await check('сховище відкидає переписування старої версії',()=>assert.rejects(()=>repo.saveSecretVault(p,altered,original.revision)));
 if(repo.kind==='postgres'){const pool=(repo as any).pool;await check('SQL trigger відкидає зміни історії в обхід сервісу',()=>assert.rejects(()=>pool.query("UPDATE fusion_core.secret_vaults SET state=jsonb_set(state,'{audit,0,actor}','\"user:tamper\"') WHERE project_id=$1",[p])));await check('SQL trigger забороняє видалення Vault',()=>assert.rejects(()=>pool.query('DELETE FROM fusion_core.secret_vaults WHERE project_id=$1',[p])));}
 const archived=await mutate('/simulations/'+futureRun.simulationId+'/archive',{confirm:true});await check('архівування закриває прогін і секрети',async()=>{assert.equal(archived.status,200);assert.equal((await repo.getMagicSceneRun(p,futureRun.simulationId))!.status,'closed');assert.equal((await repo.getSecretVault(p)).secrets.find(s=>s.id===missingId)!.status,'archived');});
 if(process.argv.includes('--browser')){
  const {build}=await import('esbuild');const output=await build({stdin:{contents:`import React from'react';import{createRoot}from'react-dom/client';import{SecretVaultPanel}from'./src/components/SecretVaultPanel';createRoot(document.getElementById('root')).render(React.createElement(SecretVaultPanel,{book:{id:${JSON.stringify(p)}}}));`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,format:'iife',platform:'browser'});app.get('/probe.js',(_q,r)=>r.type('application/javascript').send(output.outputFiles[0].text));app.get('/probe',(_q,r)=>r.send('<meta name="viewport" content="width=device-width,initial-scale=1"><div id="root"></div><script src="/probe.js"></script>'));const puppeteer=await import('puppeteer-core');const browser=await puppeteer.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{const page=await browser.newPage();await page.setViewport({width:390,height:844});await page.goto(origin+'/probe');await page.waitForSelector('[data-vault-secret]');await check('БРАУЗЕР: прихований зміст не потрапляє у DOM',async()=>{const text=await page.$eval('[data-secret-vault]',e=>e.textContent);for(const code of canaries)assert.ok(!text!.includes(code));});const article=await page.$(`[data-vault-secret="${ids[0]}"]`);const button=async(label:string)=>{for(const b of await article!.$$('button'))if(await b.evaluate(e=>e.textContent)===label)return b;throw new Error(label);};assert.equal(await (await button('Аварійно прочитати автору')).evaluate(e=>(e as HTMLButtonElement).disabled),true);await page.click('[aria-label="Підтвердження дії Vault"]');await (await button('Аварійно прочитати автору')).click();await page.waitForFunction(()=>document.body.textContent?.includes('СЕКРЕТ_ОЛЕНИ_7bd'));await check('БРАУЗЕР: Emergency Reveal лише після підтвердження',()=>{});for(const b of await page.$$('button'))if(await b.evaluate(e=>e.textContent)==='Приховати прочитане'){await b.click();break;}await page.waitForFunction(()=>!document.body.textContent?.includes('СЕКРЕТ_ОЛЕНИ_7bd'));await check('БРАУЗЕР: прочитаний секрет прибирається з DOM',()=>{});}finally{await browser.close();}}
 const workspace=await repo.getBranchWorkspace(p);const result=await mergeBranchFragment(repo,p,branch.body.branch.id,branch.body.branch.fragments[0].id,{confirm:true,expectedRevision:workspace.revision,expectedBookRevision:(await getBook(p))!.revision},actor);await check('рукопис змінюється тільки після авторського затвердження гілки',()=>assert.ok(result.stored.book.chapters[0].sections.find(s=>s.id==='next')!.content.includes(canaries[2])));
 if(repo.kind==='postgres')await check('видалення власного тестового проєкту очищає Vault через FK cascade',async()=>{await (repo as any).pool.query('DELETE FROM fusion_core.projects WHERE id=$1',[p]);assert.equal((await repo.getSecretVault(p)).revision,0);});
 console.log(`${repo.kind}: ${n} перевірок пройшло.`);
 }finally{await new Promise<void>(r=>server.close(()=>r()));}
}
async function privacyTelemetry(){
 const {generateText}=await import('../server/aiCore');const {listUsage}=await import('../server/store');
 const oldFetch=globalThis.fetch,oldWarn=console.warn,logs:string[]=[];const marker='PRIVATE_PROVIDER_CANARY_79a';
 globalThis.fetch=(async()=>({ok:false,status:503,json:async()=>({error:{message:marker,type:'service_unavailable'}})})) as any;
 console.warn=(...args:any[])=>{logs.push(args.map(String).join(' '));};
 try{await assert.rejects(()=>generateText({engine:'gpt',modelId:'gpt-4o-mini',prompt:marker,systemInstruction:marker,apiKeyOverride:'local-test-only',privateContent:true,req:{principal:{id:'owner',email:'owner@test',role:'writer',isGuest:false}},label:'vault-private-test',bookId:'vault-test'}),e=>!String(e).includes(marker));assert.ok(!logs.join(' ').includes(marker));assert.ok(!JSON.stringify(await listUsage()).includes(marker));console.log('✓ приватні помилки провайдера й повтори не розкривають prompt');console.log('✓ usage telemetry містить лише метадані');}
 finally{globalThis.fetch=oldFetch;console.warn=oldWarn;}
}
try{await suite(new MemoryCoreRepository());if(process.env.CORE_TEST_DATABASE_URL){const pool=createCorePool(process.env.CORE_TEST_DATABASE_URL);try{await runMigrations(pool,loadMigrations(resolveMigrationsDir()));await suite(new PgCoreRepository(pool));}finally{await pool.end();}}await privacyTelemetry();}finally{await fs.rm(dir,{recursive:true,force:true});}
