import assert from 'node:assert/strict';import express from 'express';import {randomUUID} from 'node:crypto';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import type {AddressInfo} from 'node:net';
import {MemoryCoreRepository} from '../server/core/memoryRepository';import {PgCoreRepository} from '../server/core/pgRepository';import type {CoreRepository} from '../server/core/types';import {createCorePool} from '../server/core';import {loadMigrations,resolveMigrationsDir,runMigrations} from '../server/core/migrate';import {computeEffective} from '../server/core/collaboration/access';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'mastery-'));process.env.DATA_DIR=dir;process.env.DATABASE_PATH=path.join(dir,'test.db');
const {registerMasteryRoutes}=await import('../server/core/masteryRoutes');const {saveBook,getBook}=await import('../server/bookStore');const {branchHash,branchCanonHash}=await import('../server/core/branches');
async function suite(repo:CoreRepository){let n=0;const check=(label:string,fn:()=>void)=>{fn();n++;console.log(`✓ ${label}`);};const P=randomUUID();await repo.upsertProject({id:P,ownerId:'owner',title:'Вправи'});await repo.upsertDocument({projectId:P,id:'ch',kind:'chapter',order:0});for(const id of ['s','secret'])await repo.upsertDocument({projectId:P,id,parentId:'ch',kind:'section',title:id,order:id==='s'?0:1});for(const [id,documentId,text] of [['p','s','Олена говорить тихо.'],['hidden','secret','Прихований текст.']])await repo.upsertParagraph({projectId:P,id,documentId,text,kind:'paragraph',order:0},'system:core_sync');const hero=await repo.createEntity({projectId:P,type:'character',name:'Олена',status:'confirmed',createdBy:'user:owner',canonical:{speech:'Стримана'}});await saveBook({book:{id:P,title:'Вправи',chapters:[{id:'ch',sections:[{id:'s',content:'Олена говорить тихо.'},{id:'secret',content:'Прихований текст.'}]}]} as any,ownerId:'owner'});const bookHash=branchHash((await getBook(P))!.book),canonHash=await branchCanonHash(repo,P);
const app=express();app.use(express.json());app.use((req,_res,next)=>{const user=String(req.headers['x-user']??'owner');req.principal={id:user==='guest'?null:user,isGuest:user==='guest',role:'writer'} as any;next();});let lastContext:any,badResponse=false,changeWhileGenerating=false;registerMasteryRoutes(app,{repo:()=>repo,access:{getBookOwnerId:async()=> 'owner',getCollabOwnerId:async()=>undefined,listAcceptedInvites:async()=>[{acceptedUserId:'editor',role:'editor'},{acceptedUserId:'reader',role:'reader'}],effectiveAccess:async({projectId,userId})=>{if(!['editor','reader'].includes(userId))return null;const e=computeEffective(projectId,userId,[],{full:false});e.scenes.s=userId==='editor'?'edit':'view';e.canWriteAny=userId==='editor';e.restricted=true;return e;}},generate:async(_req,context)=>{lastContext=context;if(changeWhileGenerating){await repo.upsertParagraph({projectId:P,id:'p',documentId:'s',text:'Зміна під час AI.',kind:'paragraph',order:0},'user:owner');}return badResponse?{questions:['?'],rewrite:'Неочікувана правка.'}:context.mode==='rewrite'?{rewrite:'Пропозиція правки.'}:{questions:['Що герой приховує?','Яка пауза змінює сцену?']};}});
const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const origin=`http://127.0.0.1:${(server.address() as AddressInfo).port}`,base=`${origin}/api/core/projects/${P}/mastery`;
const request=async(user='owner',route='',method='GET',body?:unknown)=>{const r=await fetch(base+route,{method,headers:{'x-user':user,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json()};};const get=async(user='owner')=>(await request(user)).body;const mutate=async(route:string,body:object,user='owner',method='POST')=>request(user,route,method,{...body,expectedRevision:(await get(user)).revision});
try{
assert.equal((await request('guest')).status,401);assert.equal((await request('stranger')).status,403);assert.equal((await request('reader')).status,403);n+=3;
check('каталог містить шість навичок',()=>{});assert.equal((await get()).catalog.length,6);
const initial=await get();const same={skills:['dialogue'],goal:'Сильніші голоси',expectedRevision:initial.revision};const concurrent=await Promise.all([request('owner','/plan','PUT',same),request('owner','/plan','PUT',same)]);check('конкурентне збереження плану: 200 і 409',()=>assert.deepEqual(concurrent.map(r=>r.status).sort(),[200,409]));assert.equal((await get('editor')).plan.goal,'');n++;
const scoped=await get('editor');check('сценовий доступ приховує інший матеріал',()=>assert.ok(!JSON.stringify(scoped).includes('Прихований')));assert.equal((await mutate('/exercises',{skill:'dialogue',depth:'short',genre:'Детектив',target:{kind:'paragraph',id:'hidden'}},'editor')).status,404);n++;
assert.equal((await mutate('/exercises',{skill:'unknown',depth:'short',genre:'Проза',target:{kind:'scene',id:'s'}})).status,400);n++;
const created=await mutate('/exercises',{skill:'subtext',depth:'deep',genre:'Детектив',target:{kind:'scene',id:'s'}});assert.equal(created.status,201);const e=created.body.exercise,prefix=`/exercises/${e.id}`;check('конкретна вправа з матеріалом сцени',()=>{assert.match(e.source,/Олена/);assert.match(e.instruction,/20–30/);assert.match(e.instruction,/Детектив/);});
assert.equal((await request('editor',prefix+'/versions','POST',{slot:'A',text:'Чужа редакція.',expectedRevision:(await get('editor')).revision})).status,404);n++;
assert.equal((await mutate(prefix+'/status',{status:'completed'})).status,400);n++;
await mutate(prefix+'/versions',{slot:'A',text:'Олена зупинилась біля дверей.'});await mutate(prefix+'/versions',{slot:'B',text:'Олена відповіла. Потім сховала лист.'});await mutate(prefix+'/versions',{slot:'A',text:'Олена мовчала біля дверей.'});
let view=await get();check('дві редакції й попередня версія збережені',()=>{assert.equal(view.exercises[0].versions.length,3);assert.match(view.exercises[0].versions[0].text,/зупинилась/);});assert.equal((await mutate(prefix+'/status',{status:'completed'})).status,200);view=await get();check('прогрес рахує виконану вправу',()=>assert.equal(view.progress.find(p=>p.skill==='subtext').completed,1));
await mutate(prefix+'/versions',{slot:'B',text:'Олена мовчала біля дверей.'});
assert.equal((await mutate(prefix+'/status',{status:'completed'})).status,400);n++;
check('збереження нової редакції повертає вправу в роботу',()=>{});assert.equal((await get()).progress.find(p=>p.skill==='subtext').completed,0);
await mutate(prefix+'/versions',{slot:'B',text:'Олена відповіла. Потім сховала лист.'});assert.equal((await mutate(prefix+'/status',{status:'completed'})).status,200);
const beforeMentor=(await get()).revision;const mentor=await mutate(prefix+'/mentor',{mode:'questions'});check('наставник питає з урахуванням жанру та редакцій',()=>{assert.equal(mentor.status,200);assert.equal(mentor.body.questions.length,2);assert.equal(lastContext.genre,'Детектив');assert.equal(lastContext.versions.length,2);assert.ok(lastContext.sampleCharacters>0);});assert.equal((await get()).revision,beforeMentor);n++;
assert.equal((await mutate(prefix+'/mentor',{mode:'rewrite'})).status,400);assert.equal((await mutate(prefix+'/mentor',{mode:'rewrite',confirm:'true'})).status,400);n+=2;
const rewrite=await mutate(prefix+'/mentor',{mode:'rewrite',confirm:true});check('готова правка лише на явний запит і без запису',()=>{assert.equal(rewrite.status,200);assert.equal(rewrite.body.rewrite,'Пропозиція правки.');});assert.equal((await get()).revision,beforeMentor);n++;
badResponse=true;const defensive=await mutate(prefix+'/mentor',{mode:'questions'});check('зайва готова правка не виходить через режим запитань',()=>assert.equal(defensive.body.rewrite,undefined));badResponse=false;
let savedExercise=(await get()).exercises[0];assert.equal((await mutate(prefix+'/branch',{versionId:savedExercise.versions[2].id,expectedBranchRevision:0})).status,400);n++;
const branch=await mutate(prefix+'/branch',{versionId:savedExercise.versions[2].id,expectedBranchRevision:0,confirm:true});check('редакція стає лише ізольованою гілкою',()=>{assert.equal(branch.status,201);assert.equal(branch.body.branch.fragments[0].text,savedExercise.versions[2].text);});
const other=await mutate('/exercises',{skill:'emotion',depth:'short',genre:'Проза',target:{kind:'character',id:hero.id}});assert.equal(other.status,201);n++;assert.equal((await mutate(`/exercises/${other.body.exercise.id}/status`,{status:'rejected',reason:''})).status,400);n++;assert.equal((await mutate(`/exercises/${other.body.exercise.id}/status`,{status:'rejected',reason:'Не відповідає задуму.'})).status,200);n++;assert.equal((await mutate(`/exercises/${other.body.exercise.id}/versions`,{slot:'A',text:'Не можна.'})).status,409);n++;
const pExercise=await mutate('/exercises',{skill:'dialogue',depth:'short',genre:'Драма',target:{kind:'paragraph',id:'p'}});changeWhileGenerating=true;const stale=await mutate(`/exercises/${pExercise.body.exercise.id}/mentor`,{mode:'questions'});changeWhileGenerating=false;check('зміна матеріалу під час AI відхиляє відповідь',()=>assert.equal(stale.status,409));assert.equal((await get()).exercises.find(e=>e.id===pExercise.body.exercise.id).needsUpdate,true);n++;
check('вправи, наставник і гілка не змінюють рукопис',()=>{});assert.equal(branchHash((await getBook(P))!.book),bookHash);check('канон незмінний',()=>{});assert.equal(await branchCanonHash(repo,P),canonHash);
await repo.upsertParagraph({projectId:P,id:'p',documentId:'s',text:'Олена говорить тихо.',kind:'paragraph',order:0},'system:core_sync');
if(process.argv.includes('--browser')){
 const {build}=await import('esbuild');const output=await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import{WriterMasteryPage}from'./src/components/WriterMasteryPage';createRoot(document.getElementById('root')).render(React.createElement(WriterMasteryPage,{book:{id:${JSON.stringify(P)}}}));`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,format:'iife',platform:'browser'});const css=(await Promise.all((await fs.readdir('dist/assets')).filter(x=>x.endsWith('.css')).map(x=>fs.readFile(path.join('dist/assets',x),'utf8')))).join('\n');app.get('/probe.css',(_q,r)=>r.type('text/css').send(css));app.get('/probe.js',(_q,r)=>r.type('application/javascript').send(output.outputFiles[0].text));app.get('/probe',(_q,r)=>r.send('<meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/probe.css"><div id="root"></div><script src="/probe.js"></script>'));const puppeteer=await import('puppeteer-core');const browser=await puppeteer.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{const page=await browser.newPage();await page.setViewport({width:390,height:844});await page.goto(origin+'/probe');await page.waitForSelector('[aria-label="Історія вправ"]');await page.select('[aria-label="Історія вправ"]',e.id);await page.waitForSelector('[aria-label="Авторська редакція A"]');assert.match(await page.$eval('[aria-label="Авторська редакція A"]',x=>(x as HTMLTextAreaElement).value),/мовчала/);assert.match(await page.$eval('[aria-label="Авторська редакція B"]',x=>(x as HTMLTextAreaElement).value),/сховала/);check('БРАУЗЕР: обидві авторські редакції доступні',()=>{});await page.select('[aria-label="Версії редакцій"]',e.versions[0]?.id??savedExercise.versions[0].id);assert.match((await page.$eval('[data-writer-mastery]',x=>x.textContent))!,/зупинилась/);check('БРАУЗЕР: попередня редакція читається в історії',()=>{});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);check('БРАУЗЕР: ширина 390 px без переповнення',()=>{});await page.select('[aria-label="Матеріал вправи"]','s');for(const button of await page.$$('button'))if((await button.evaluate(x=>x.textContent))==='Отримати вправу'){await button.click();break;}
await page.waitForFunction(old=>(document.querySelector('[aria-label="Історія вправ"]') as HTMLSelectElement)?.value!==old,e.id);await page.waitForFunction(()=>(document.querySelector('[aria-label="Авторська редакція A"]') as HTMLTextAreaElement)?.value==='');
await page.type('[aria-label="Авторська редакція A"]','Перший голос автора.');for(const button of await page.$$('button'))if((await button.evaluate(x=>x.textContent))==='Зберегти A'){await button.click();break;}await page.waitForFunction(()=>document.querySelectorAll('[aria-label="Версії редакцій"] option').length===2);
await page.type('[aria-label="Авторська редакція B"]','Другий голос автора.');for(const button of await page.$$('button'))if((await button.evaluate(x=>x.textContent))==='Зберегти B'){await button.click();break;}await page.waitForFunction(()=>document.querySelectorAll('[aria-label="Версії редакцій"] option').length===3);
for(const button of await page.$$('button'))if((await button.evaluate(x=>x.textContent))==='Завершити вправу'){await button.click();break;}await page.waitForFunction(()=>{const x=document.querySelector('[aria-label="Історія вправ"]') as HTMLSelectElement;return x.selectedOptions[0]?.textContent?.includes('completed');});
check('БРАУЗЕР: створення, дві редакції та завершення вправи',()=>{});assert.equal((await get()).exercises.at(-1).status,'completed');assert.equal(branchHash((await getBook(P))!.book),bookHash);n++;await page.screenshot({path:`/tmp/mastery-${repo.kind}.png`,fullPage:true});}finally{await browser.close();}
}
console.log(`${repo.kind}: ${n} перевірок пройшло.`);
}finally{await new Promise<void>(r=>server.close(()=>r()));}}
try{await suite(new MemoryCoreRepository());if(process.env.CORE_TEST_DATABASE_URL){const pool=createCorePool(process.env.CORE_TEST_DATABASE_URL);try{await runMigrations(pool,loadMigrations(resolveMigrationsDir()));await suite(new PgCoreRepository(pool));}finally{await pool.end();}}}finally{await fs.rm(dir,{recursive:true,force:true});}
