import assert from 'node:assert/strict';import express from 'express';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';import type {AddressInfo} from 'node:net';
import {MemoryCoreRepository} from '../server/core/memoryRepository';import {PgCoreRepository} from '../server/core/pgRepository';import type {CoreRepository} from '../server/core/types';import {createCorePool} from '../server/core';import {loadMigrations,resolveMigrationsDir,runMigrations} from '../server/core/migrate';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'magic-'));process.env.DATA_DIR=dir;process.env.DATABASE_PATH=path.join(dir,'test.db');const {saveBook,getBook}=await import('../server/bookStore');const {syncBookToCore}=await import('../server/core/sync');const {registerMagicSceneRoutes}=await import('../server/core/magicSceneRoutes');const {refreshMemoryReview}=await import('../server/core/characterMemory');const {branchHash,branchCanonHash}=await import('../server/core/branches');
async function suite(repo:CoreRepository){let n=0;const check=(label:string,fn:()=>void)=>{fn();n++;console.log(`✓ ${label}`);};const P=randomUUID(),actor='user:owner';await repo.upsertProject({id:P,ownerId:'owner',title:'Magic Scene'});
const stored=await saveBook({book:{id:P,title:'Magic Scene',chapters:[{id:'ch',sections:[{id:'earlier',title:'Раніше',content:'Колишня зустріч.'},{id:'s',title:'Перша сцена',content:'Порожня кімната.'},{id:'next',title:'Друга сцена',content:'Пізніша зустріч.'},{id:'future',title:'Майбутня сцена',content:'Секрет стане відомим згодом.'}]}]} as any,ownerId:'owner'});await syncBookToCore(repo,stored);
const heroes=[];for(const name of ['Олена','Марко','Анна']){const hero=await repo.createEntity({projectId:P,type:'character',name,status:'confirmed',createdBy:actor});heroes.push(hero);await repo.upsertCharacterAgent({projectId:P,characterId:hero.id,autonomyLevel:'scene',actor,agentConfig:{}});}
const [h1,h2,h3]=heroes;for(const [hero,secret] of [[h1,'ПРИВАТНИЙ_КОД_ОЛЕНИ'],[h2,'ПРИВАТНИЙ_КОД_МАРКА']] as const)await repo.addCharacterMemory({projectId:P,characterId:hero.id,memoryType:'recollection',content:secret,canonRevision:(await repo.getProject(P))!.revision,sourceEventKind:'author',sceneId:'earlier',origin:'author',createdBy:actor,status:'confirmed',visibility:'hidden'});
await repo.addCharacterMemory({projectId:P,characterId:h1.id,memoryType:'knowledge',content:'МАЙБУТНЄ_ЗНАННЯ',canonRevision:(await repo.getProject(P))!.revision,sourceEventKind:'author',sceneId:'future',origin:'author',createdBy:actor,status:'confirmed',visibility:'hidden'});
const originalMemories=branchHash(await repo.listCharacterMemories(P,{limit:1000}));const originalHash=branchHash((await getBook(P))!.book),canonHash=await branchCanonHash(repo,P);let selectedRepo=repo,voiceBad=false,writerBad=false,awaitAuthor=false,onlySelf=false,slow=false,failMemory=false,overlap=false;let release:(()=>void)|undefined;const contexts:any[]=[],writerContexts:any[]=[];
const proxy=new Proxy(repo,{get(t,k){if(k==='addCharacterMemory')return async(input:any)=>{if(failMemory&&input.dedupeKey?.startsWith('magic:')){failMemory=false;throw new Error('simulated memory failure');}return t.addCharacterMemory(input);};const v=Reflect.get(t,k);return typeof v==='function'?v.bind(t):v;}});selectedRepo=proxy;
const app=express();app.use(express.json());app.use((req,_res,next)=>{const user=String(req.headers['x-user']??'owner');req.principal={id:user==='guest'?null:user,isGuest:user==='guest',role:'writer'} as any;next();});registerMagicSceneRoutes(app,{repo:()=>selectedRepo,access:{getBookOwnerId:async()=> 'owner',getCollabOwnerId:async()=>undefined,listAcceptedInvites:async()=>[{acceptedUserId:'reader',role:'reader'}]},engines:async()=>({decide:async()=>({action:'answer',source:'mock',awaitingAuthor:awaitAuthor}),voice:async context=>{contexts.push(context);if(slow)await new Promise<void>(r=>{release=r;});if(voiceBad)return {speech:5};return {speech:`Слова героя ${context.hero['name']} на ході ${context.turn}.`,actionText:'Показує лист.',privateThought:`ВЛАСНА_ДУМКА_${context.hero['id']}`,intent:'Приховати тривогу.',...(onlySelf?{audience:[context.hero['id']]}:{})};},writer:async context=>{writerContexts.push(context);return overlap?{fragments:['Герой підняв лист.','Інший герой відповів.'].map(text=>({text,eventIds:(context.events as any[]).map(e=>e.id)}))}:writerBad?{fragments:[{text:'Вигадка',eventIds:['missing']}]}:{fragments:[{text:'Герої обмінялися словами біля листа. [/emotion:тривога @Олена]',eventIds:(context.events as any[]).map(e=>e.id)}]};}})});
const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const origin=`http://127.0.0.1:${(server.address() as AddressInfo).port}`,base=`${origin}/api/core/projects/${P}`;
const req=async(route:string,method='GET',body?:unknown,user='owner')=>{const r=await fetch(base+route,{method,headers:{'x-user':user,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:r.status,body:await r.json()};};const list=async()=>(await req('/magic-scenes')).body;const run=async(id:string)=>(await req(`/simulations/${id}/events`)).body.run;const mutation=async(id:string,op:string,body:object={})=>req(`/simulations/${id}/${op}`,'POST',{...body,expectedRevision:(await run(id)).revision});const start=async(scene='s',participants=[h1.id,h2.id],maxTurns=2)=>req(`/scenes/${scene}/simulations`,'POST',{participants,goal:'Знайти домовленість',constraints:'Не змінювати затверджених фактів.',maxTurns});
try{
assert.equal((await req('/magic-scenes','GET',undefined,'guest')).status,401);assert.equal((await req('/magic-scenes','GET',undefined,'stranger')).status,403);assert.equal((await req('/magic-scenes','GET',undefined,'reader')).status,403);n+=3;
assert.equal((await start('s',[h1.id])).status,400);assert.equal((await start('s',[h1.id,h1.id])).status,400);assert.equal((await start('missing')).status,404);n+=3;
const created=await start();assert.equal(created.status,201,JSON.stringify(created.body));const id=created.body.run.simulationId;check('режисер задає порядок, межі й ліміт',()=>{assert.deepEqual(created.body.run.participants,[h1.id,h2.id]);assert.equal(created.body.run.maxTurns,2);});
const state=await run(id),requestId=randomUUID(),otherRequestId=randomUUID();const simultaneous=await Promise.all([req(`/simulations/${id}/step`,'POST',{expectedRevision:state.revision,requestId}),req(`/simulations/${id}/step`,'POST',{expectedRevision:state.revision,requestId:otherRequestId})]);check('один із конкурентних ходів прийнятий, другий — 409',()=>assert.deepEqual(simultaneous.map(x=>x.status).sort(),[200,409]));
const repeated=await req(`/simulations/${id}/step`,'POST',{expectedRevision:state.revision,requestId:simultaneous[0].status===200?requestId:otherRequestId});check('ідентичний повтор не додає ходу',()=>{assert.equal(repeated.status,200);assert.equal(repeated.body.run.events.length,1);});
assert.equal((await mutation(id,'step',{requestId:randomUUID()})).status,200);n++;const first=contexts[0],second=contexts[1];check('контексти героїв ізольовані',()=>{assert.ok(JSON.stringify(first).includes('ПРИВАТНИЙ_КОД_ОЛЕНИ'));assert.ok(!JSON.stringify(first).includes('ПРИВАТНИЙ_КОД_МАРКА'));assert.ok(JSON.stringify(second).includes('ПРИВАТНИЙ_КОД_МАРКА'));assert.ok(!JSON.stringify(second).includes('ПРИВАТНИЙ_КОД_ОЛЕНИ'));assert.ok(!JSON.stringify(second).includes('ВЛАСНА_ДУМКА_'+h1.id));assert.ok(!JSON.stringify(first).includes('МАЙБУТНЄ_ЗНАННЯ'));});
check('другий герой бачить лише спостережувану дію першого',()=>{assert.equal(second.observed.length,1);assert.equal(second.observed[0].action,undefined);});check('ліміт завершив прогін',()=>{});assert.equal((await run(id)).status,'closed');assert.equal((await mutation(id,'step',{requestId:randomUUID()})).status,409);n++;
writerBad=true;assert.equal((await mutation(id,'draft')).status,400);writerBad=false;n++;assert.equal((await mutation(id,'draft')).status,200);n++;const drafted=await run(id),f=drafted.fragments[0];check('літературний автор не отримав приватних думок',()=>assert.ok(!JSON.stringify(writerContexts.at(-1)).includes('ВЛАСНА_ДУМКА')));check('теги лишилися окремими пропозиціями',()=>{assert.equal(f.tags.length,1);assert.ok(!f.text.includes('[/emotion:'));});assert.equal(branchHash((await getBook(P))!.book),originalHash);assert.equal(await branchCanonHash(repo,P),canonHash);assert.equal(branchHash(await repo.listCharacterMemories(P,{limit:1000})),originalMemories);n+=3;
const beforeCheck=(await run(id)).revision;assert.equal((await mutation(id,'check')).status,200);assert.equal((await run(id)).revision,beforeCheck);n++;
let workspace=await list();assert.equal((await mutation(id,'approve',{fragmentId:f.id,expectedBranchRevision:workspace.branchRevision,expectedBookRevision:workspace.bookRevision})).status,400);n++;
failMemory=true;const failed=await mutation(id,'approve',{fragmentId:f.id,confirm:true,tagIds:[],expectedBranchRevision:workspace.branchRevision,expectedBookRevision:workspace.bookRevision,acknowledgeWarnings:true});assert.equal(failed.status,500,JSON.stringify(failed.body));const appliedRevision=(await getBook(P))!.revision;n++;workspace=await list();const approved=await mutation(id,'approve',{fragmentId:f.id,confirm:true,tagIds:[],expectedBranchRevision:workspace.branchRevision,expectedBookRevision:workspace.bookRevision,acknowledgeWarnings:true});check('повтор після збою пам’яті не дублює рукопис',()=>{assert.equal(approved.status,200,JSON.stringify(approved.body));assert.equal((approved.body.book.chapters[0].sections.find(s=>s.id==='s').content.match(/Герої обмінялися/g)||[]).length,1);});assert.equal((await getBook(P))!.revision,appliedRevision);n++;
const magicMemories=await repo.listCharacterMemories(P,{simulationId:null,limit:1000});check('пам’ять кожного учасника оновлено лише спостережуваними подіями',()=>{for(const h of [h1,h2])assert.equal(magicMemories.filter(m=>m.characterId===h.id&&m.dedupeKey?.startsWith('magic:')).length,2);assert.ok(!magicMemories.filter(m=>m.dedupeKey?.startsWith('magic:')).some(m=>m.content.includes('ВЛАСНА_ДУМКА')));assert.ok(magicMemories.filter(m=>m.dedupeKey?.startsWith('magic:')).every(m=>m.sourceParagraphIds.length>0&&m.evidenceHash));});
const secondScene=await start('next');assert.equal(secondScene.status,201,JSON.stringify(secondScene.body));const nextId=secondScene.body.run.simulationId;assert.equal((await mutation(nextId,'step',{requestId:randomUUID()})).status,200);check('друга сцена враховує затверджені спогади першої',()=>assert.ok(JSON.stringify(contexts.at(-1)).includes('Слова героя Олена на ході 1.')));
const privateRun=(await start('next',[h1.id,h2.id,h3.id],3)).body.run.simulationId;onlySelf=true;assert.equal((await mutation(privateRun,'step',{requestId:randomUUID()})).status,200);onlySelf=false;assert.equal((await mutation(privateRun,'step',{requestId:randomUUID()})).status,200);check('неспостережувані події не потрапляють іншому агенту',()=>assert.equal(contexts.at(-1).observed.length,0));assert.equal((await mutation(privateRun,'step',{requestId:randomUUID()})).status,200);check('третій агент працює своїм ходом',()=>assert.equal(contexts.at(-1).hero.id,h3.id));
const recover=(await start('next')).body.run.simulationId;voiceBad=true;assert.equal((await mutation(recover,'step',{requestId:randomUUID()})).status,400);voiceBad=false;const afterFailure=await run(recover);check('збій голосу не залишає напівходу',()=>{assert.equal(afterFailure.events.length,0);assert.equal(afterFailure.busy,null);});
awaitAuthor=true;assert.equal((await mutation(recover,'step',{requestId:randomUUID()})).status,200);awaitAuthor=false;assert.equal((await run(recover)).status,'paused');n++;assert.equal((await mutation(recover,'pause',{status:'active'})).status,200);n++;assert.equal((await mutation(recover,'step',{requestId:randomUUID(),authorAction:'answer'})).status,200);n++;
const slowId=(await start('next')).body.run.simulationId;slow=true;const pending=mutation(slowId,'step',{requestId:randomUUID()});while(!release)await new Promise(r=>setTimeout(r,5));assert.equal((await mutation(slowId,'pause',{status:'paused'})).status,200);release();slow=false;release=undefined;const cancelled=await pending;check('пауза відкидає відповідь уже запущеної моделі',()=>assert.equal(cancelled.status,409));assert.equal((await run(slowId)).events.length,0);n++;
const rejected=(await start('next')).body.run.simulationId;await mutation(rejected,'step',{requestId:randomUUID()});await mutation(rejected,'draft');const rejectedFragment=(await run(rejected)).fragments[0];assert.equal((await mutation(rejected,'reject',{fragmentId:rejectedFragment.id})).status,200);workspace=await list();assert.equal((await mutation(rejected,'approve',{fragmentId:rejectedFragment.id,confirm:true,expectedBranchRevision:workspace.branchRevision,expectedBookRevision:workspace.bookRevision})).status,409);n+=2;
const taggedId=(await start('next')).body.run.simulationId;await mutation(taggedId,'step',{requestId:randomUUID()});await mutation(taggedId,'draft');const tagged=(await run(taggedId)).fragments[0];workspace=await list();const taggedApproval=await mutation(taggedId,'approve',{fragmentId:tagged.id,confirm:true,tagIds:[tagged.tags[0].id],expectedBranchRevision:workspace.branchRevision,expectedBookRevision:workspace.bookRevision,acknowledgeWarnings:true});check('тег переноситься в канон лише після вибору автора',()=>assert.equal(taggedApproval.status,200,JSON.stringify(taggedApproval.body)));assert.ok(await repo.resolveAlias(P,'emotion','тривога'));assert.equal(await repo.resolveAlias(P,'character','Олена'),h1.id);assert.equal((await repo.listEntities(P,'character')).filter(c=>c.name==='Олена').length,1);n++;
const overlapId=(await start('next')).body.run.simulationId;await mutation(overlapId,'step',{requestId:randomUUID()});overlap=true;await mutation(overlapId,'draft');overlap=false;const overlapFragments=(await run(overlapId)).fragments;
for(const fragment of overlapFragments){workspace=await list();const accepted=await mutation(overlapId,'approve',{fragmentId:fragment.id,confirm:true,tagIds:[],expectedBranchRevision:workspace.branchRevision,expectedBookRevision:workspace.bookRevision,acknowledgeWarnings:true});assert.equal(accepted.status,200,JSON.stringify(accepted.body));n++;}
const overlapEvent=(await run(overlapId)).events[0];const overlapMemories=await repo.listCharacterMemories(P,{simulationId:null,limit:1000});check('спільні події різних фрагментів не дублюють памʼять',()=>assert.equal(overlapMemories.filter(m=>m.sourceEventId===overlapEvent.id).length,2));
if(process.argv.includes('--browser')){
 const {build}=await import('esbuild');const output=await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import{MagicScenePage}from'./src/components/MagicScenePage';createRoot(document.getElementById('root')).render(React.createElement(MagicScenePage,{book:{id:${JSON.stringify(P)}}}));`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,format:'iife',platform:'browser'});const css=(await Promise.all((await fs.readdir('dist/assets')).filter(x=>x.endsWith('.css')).map(x=>fs.readFile(path.join('dist/assets',x),'utf8')))).join('\n');app.get('/probe.css',(_q,r)=>r.type('text/css').send(css));app.get('/probe.js',(_q,r)=>r.type('application/javascript').send(output.outputFiles[0].text));app.get('/probe',(_q,r)=>r.send('<meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/probe.css"><div id="root"></div><script src="/probe.js"></script>'));const puppeteer=await import('puppeteer-core');const browser=await puppeteer.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{const page=await browser.newPage();await page.setViewport({width:390,height:844});await page.goto(origin+'/probe');await page.waitForSelector('[aria-label="Прогін Magic Scene"]');await page.select('[aria-label="Прогін Magic Scene"]',id);await page.waitForFunction(()=>document.body.textContent?.includes('Хід 1'));check('БРАУЗЕР: протокол показує послідовні ходи',()=>{});for(const button of await page.$$('button'))if((await button.evaluate(x=>x.textContent))==='Літературний текст'){await button.click();break;}await page.waitForFunction(()=>document.body.textContent?.includes('Герої обмінялися'));check('БРАУЗЕР: літературний текст і затверджений статус доступні',()=>{});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);check('БРАУЗЕР: телефон без горизонтального переповнення',()=>{});await page.select('[aria-label="Сцена Magic Scene"]','next');
for(const hero of [h1,h2])await page.click(`[data-magic-character="${hero.id}"]`);
await page.type('[aria-label="Мета Magic Scene"]','Браузерна зустріч');await page.click('[aria-label="Ліміт ходів Magic Scene"]',{clickCount:3});await page.keyboard.press('Backspace');await page.type('[aria-label="Ліміт ходів Magic Scene"]','2');
const click=async(text:string)=>{for(const button of await page.$$('button'))if((await button.evaluate(x=>x.textContent))===text){await button.click();return;}throw new Error(`Немає кнопки ${text}`);};
await click('Почати Magic Scene');await page.waitForFunction(()=>{const s=document.querySelector('[aria-label="Прогін Magic Scene"]') as HTMLSelectElement;return s.selectedOptions[0]?.textContent?.includes('Браузерна зустріч')||!!document.querySelector('[role=alert]');});
assert.equal(await page.$eval('[data-magic-scene]',x=>x.querySelector('[role=alert]')?.textContent??''),'');await click('Наступний хід');await page.waitForFunction(()=>document.body.textContent?.includes('Ходів: 1/2.'));await click('Наступний хід');await page.waitForFunction(()=>document.body.textContent?.includes('Ходів: 2/2.'));await click('Створити літературну чернетку');await page.waitForFunction(()=>document.body.textContent?.includes('Статус: draft'));
await page.waitForNetworkIdle({idleTime:100,timeout:5000});const beforeApproval=(await getBook(P))!.revision;for(const label of await page.$$('label'))if((await label.evaluate(x=>x.textContent??'')).trim().startsWith('Підтверджую вибраний')){await (await label.$('input'))!.click();break;}
await click('Затвердити цей фрагмент і видимі спогади');await page.waitForFunction(()=>document.body.textContent?.includes('Статус: accepted')||!!document.querySelector('[role=alert]'));assert.equal(await page.$eval('[data-magic-scene]',x=>x.querySelector('[role=alert]')?.textContent??''),'');assert.equal((await getBook(P))!.revision,beforeApproval+1);check('БРАУЗЕР: створення, два ходи, чернетка й явне затвердження',()=>{});
await page.screenshot({path:`/tmp/magic-scene-${repo.kind}.png`,fullPage:true});}finally{await browser.close();}
}
const proof=await repo.getParagraph(P,magicMemories.find(m=>m.dedupeKey?.startsWith('magic:'))!.sourceParagraphIds[0]);assert.ok(proof);
await repo.upsertParagraph({projectId:P,id:proof.id,documentId:proof.documentId,order:proof.order,kind:proof.kind,text:'Змінений автором доказ.'},actor);
const review=await refreshMemoryReview(repo,P,{paragraphIds:[proof.id]});check('редагування доказу позначає затверджені спогади для перевірки',()=>assert.ok(review.flagged>=4));
check('зміна канонної памʼяті зупиняє застарілий прогін',()=>{});assert.equal((await mutation(nextId,'step',{requestId:randomUUID()})).status,409);
const unsyncedId=(await start('next')).body.run.simulationId;const currentBook=(await getBook(P))!;const changedBook:any=structuredClone(currentBook.book);changedBook.chapters[0].sections.find(s=>s.id==='next').content='Зміна ще не синхронізована до ядра.';await saveBook({book:changedBook,expectedRevision:currentBook.revision});check('зміна серверної книги зупиняє прогін до фонового core_sync',()=>{});assert.equal((await mutation(unsyncedId,'step',{requestId:randomUUID()})).status,409);
console.log(`${repo.kind}: ${n} перевірок пройшло.`);
}finally{await new Promise<void>(r=>server.close(()=>r()));}}
try{await suite(new MemoryCoreRepository());if(process.env.CORE_TEST_DATABASE_URL){const pool=createCorePool(process.env.CORE_TEST_DATABASE_URL);try{await runMigrations(pool,loadMigrations(resolveMigrationsDir()));await suite(new PgCoreRepository(pool));}finally{await pool.end();}}}finally{await fs.rm(dir,{recursive:true,force:true});}
