import assert from 'node:assert/strict';
import express from 'express';import type {AddressInfo} from 'node:net';
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {MemoryCoreRepository} from '../server/core/memoryRepository';import {PgCoreRepository} from '../server/core/pgRepository';import {createCorePool} from '../server/core';import {loadMigrations,resolveMigrationsDir,runMigrations} from '../server/core/migrate';import type {CoreRepository} from '../server/core/types';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'branches-'));process.env.DATA_DIR=dir;process.env.DATABASE_PATH=path.join(dir,'test.db');
const {registerBranchRoutes}=await import('../server/core/branchRoutes');
const {saveBook,getBook}=await import('../server/bookStore');const {branchHash,branchCanonHash,createBranch,putBranchFragment,mergeBranchFragment,checkBranch,saveBranches,branchSnapshot}=await import('../server/core/branches');
async function suite(repo:CoreRepository){let n=0;const check=(label:string,fn:()=>void)=>{fn();n++;console.log(`✓ ${label}`);};const P=randomUUID();await repo.upsertProject({id:P,ownerId:'owner',title:'Гілки'});await repo.upsertDocument({projectId:P,id:'ch',kind:'chapter',order:0});await repo.upsertDocument({projectId:P,id:'s',parentId:'ch',kind:'section',order:0});await repo.upsertParagraph({projectId:P,id:'p',documentId:'s',text:'Оригінал.',kind:'paragraph',order:0},'system:core_sync');const actor='user:owner';const stored=await saveBook({book:{id:P,title:'Гілки',chapters:[{id:'ch',sections:[{id:'s',content:'Оригінал.'}]}]} as any,ownerId:'owner'});
const original=branchHash(stored.book),canon=await branchCanonHash(repo,P);let r=await createBranch(repo,P,stored,{name:'Альтернатива',expectedRevision:0},actor);const id=r.branch.id;
check('створення зберегло основу',()=>assert.equal(r.branch.baseBookHash,original));await assert.rejects(createBranch(repo,P,stored,{name:'Застаріла',expectedRevision:0},actor));n++;
r=await putBranchFragment(repo,P,id,{paragraphId:'p',sectionId:'s',text:'Інший вибір.',expectedRevision:r.revision},actor);const f=r.branch.fragments[0];await checkBranch(repo,P,r.branch);check('чернетка і перевірки не змінили рукопис',()=>assert.equal(branchHash((stored).book),original));check('канон не змінений',()=>assert.equal(r.branch.baseCanonHash,canon));assert.equal(branchHash((await getBook(P))!.book),original);assert.equal(await branchCanonHash(repo,P),canon);n+=2;
let second=await createBranch(repo,P,(await getBook(P))!,{name:'Друга',expectedRevision:r.revision},actor);second=await putBranchFragment(repo,P,second.branch.id,{sectionId:'s',text:'Додатковий фрагмент.',expectedRevision:second.revision},actor);check('гілки незалежні',()=>assert.equal(second.branch.fragments.length,1));
await assert.rejects(mergeBranchFragment(repo,P,id,f.id,{confirm:false,expectedRevision:second.revision,expectedBookRevision:stored.revision},actor));n++;await assert.rejects(mergeBranchFragment(repo,P,id,f.id,{confirm:true,expectedRevision:second.revision,expectedBookRevision:0},actor));n++;
const merged=await mergeBranchFragment(repo,P,id,f.id,{confirm:true,expectedRevision:second.revision,expectedBookRevision:stored.revision},actor);check('лише підтверджений фрагмент перенесено',()=>assert.equal((merged.stored.book as any).chapters[0].sections[0].content,'Інший вибір.'));check('канон після перенесення не змінений',()=>assert.equal(merged.branch.baseCanonHash,canon));assert.equal(await branchCanonHash(repo,P),canon);n++;
const duplicate=await mergeBranchFragment(repo,P,id,f.id,{confirm:true,expectedRevision:merged.revision,expectedBookRevision:merged.stored.revision},actor);check('повтор підтвердження не змінює ревізію',()=>assert.equal(duplicate.stored.revision,merged.stored.revision));
let failure=true;const faulty=new Proxy(repo,{get(t,k){if(k==='saveBranchWorkspace')return async(p:string,state:any,expected:number)=>{if(failure&&state.branches.some((b:any)=>b.id===second.branch.id&&b.fragments.some((f:any)=>f.status==='accepted'))){failure=false;throw new Error('simulated finalization failure');}return t.saveBranchWorkspace(p,state,expected);};const value=Reflect.get(t,k);return typeof value==='function'?value.bind(t):value;}});
await assert.rejects(mergeBranchFragment(faulty,P,second.branch.id,second.branch.fragments[0].id,{confirm:true,expectedRevision:duplicate.revision,expectedBookRevision:duplicate.stored.revision},actor));n++;const afterFailure=(await getBook(P))!;const pending=await repo.getBranchWorkspace(P);const retry=await mergeBranchFragment(repo,P,second.branch.id,second.branch.fragments[0].id,{confirm:true,expectedRevision:pending.revision,expectedBookRevision:afterFailure.revision},actor);check('збій завершення не дублює текст при повторі',()=>{assert.equal(retry.stored.revision,afterFailure.revision);assert.equal(((retry.stored.book as any).chapters[0].sections[0].content.match(/Додатковий фрагмент/g)||[]).length,1);});
const state=await repo.getBranchWorkspace(P);state.branches[0].name='Нова назва';state.branches[0].status='archived';branchSnapshot(state.branches[0],actor);await saveBranches(repo,P,state,state.revision);await assert.rejects(putBranchFragment(repo,P,id,{sectionId:'s',text:'Не можна.',expectedRevision:state.revision},actor));n++;check('історія зберігає попередню назву',()=>assert.equal(state.branches[0].history[0].name,'Альтернатива'));
await assert.rejects(createBranch(repo,P,retry.stored,{name:'Помилка',expectedRevision:state.revision,initialFragment:{sectionId:'missing',text:'Текст',sourceProposalId:'fake'}},actor));assert.equal((await repo.getBranchWorkspace(P)).revision,state.revision);n++;const app=express();app.use(express.json());app.use((req,_res,next)=>{const user=String(req.headers['x-user']??'owner');req.principal={id:user==='guest'?null:user,isGuest:user==='guest',role:'writer'} as any;next();});
registerBranchRoutes(app,{repo:()=>repo,access:{getBookOwnerId:async()=> 'owner',getCollabOwnerId:async()=>undefined,listAcceptedInvites:async()=>[]},generate:async()=>({hypotheses:[{text:'Гіпотеза.',reason:'Інший вибір.'}]})});
const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const origin=`http://127.0.0.1:${(server.address() as AddressInfo).port}`,base=`${origin}/api/core/projects/${P}/branches`;
try{const request=async(user:string,route='',method='GET',body?:unknown)=>{const res=await fetch(base+route,{method,headers:{'x-user':user,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:res.status,body:await res.json()};};
check('API: сторонній не читає гілки',()=>{});assert.equal((await request('stranger')).status,403);assert.equal((await request('guest')).status,401);n++;
const workspace=(await request('owner')).body;const response=await request('owner','','POST',{name:'Браузерна гілка',expectedRevision:workspace.revision});assert.equal(response.status,201);n++;
const beforeAI=branchHash((await getBook(P))!.book);const ai=await request('owner',`/${response.body.branch.id}/hypotheses`,'POST',{});check('API: гіпотеза лишається пропозицією',()=>{assert.equal(ai.status,200);assert.equal(ai.body.hypotheses[0].text,'Гіпотеза.');});assert.equal(branchHash((await getBook(P))!.book),beforeAI);n++;
for(const kind of ['interview','scene'] as const){
 const hero=await repo.createEntity({projectId:P,type:'character',name:`Герой ${kind}`,status:'confirmed',createdBy:actor});
 const sim=await repo.addSimulation({projectId:P,kind,characterId:hero.id,sceneId:'s',baseBookRevision:(await getBook(P))!.revision,title:kind,createdBy:actor});
 const proposal=await repo.addCanonProposal({projectId:P,simulationId:sim.id,characterId:hero.id,kind:'fragment',proposedChange:{text:`Фрагмент ${kind}.`},createdBy:'ai:voice'});
 const before=branchHash((await getBook(P))!.book),current=(await request('owner')).body;
 const isolated=await request('owner','/from-proposal','POST',{proposalId:proposal.id,sectionId:'s',expectedRevision:current.revision,acknowledgeStale:true});assert.equal(isolated.status,201,JSON.stringify(isolated.body));
 check(`API: ${kind} використовує ізольовану гілку`,()=>{assert.equal(isolated.body.branch.source,kind==='scene'?'magic_scene':'interview');assert.equal(isolated.body.branch.fragments.length,1);});assert.equal(branchHash((await getBook(P))!.book),before);assert.equal((await repo.getCanonProposal(P,proposal.id))!.status,'pending');n+=2;
 const fragment=isolated.body.branch.fragments[0];const approve=await request('owner',`/${isolated.body.branch.id}/fragments/${fragment.id}/merge`,'POST',{confirm:true,expectedRevision:isolated.body.revision,expectedBookRevision:(await getBook(P))!.revision});assert.equal(approve.status,200,JSON.stringify(approve.body));check(`API: ${kind} затверджується окремим фрагментом`,()=>assert.equal(approve.body.branch.fragments[0].status,'accepted'));assert.equal((await repo.getCanonProposal(P,proposal.id))!.status,'accepted');n++;
}
const beforeCanonBranch=(await request('owner')).body;
const canonBranch=await request('owner','','POST',{name:'Зміни канону',expectedRevision:beforeCanonBranch.revision});
const canonFragment=await request('owner',`/${canonBranch.body.branch.id}/fragments`,'POST',{sectionId:'s',text:'Свіжа альтернатива.',expectedRevision:canonBranch.body.revision});
await repo.createEntity({projectId:P,type:'character',name:'Новий канон',status:'confirmed',createdBy:actor});
const mergeInput={confirm:true,expectedRevision:canonFragment.body.revision,expectedBookRevision:(await getBook(P))!.revision};
check('API: зміна канону потребує нового підтвердження',()=>{});assert.equal((await request('owner',`/${canonBranch.body.branch.id}/fragments/${canonFragment.body.branch.fragments[0].id}/merge`,'POST',mergeInput)).status,409);
check('API: текстове false не обходить підтвердження',()=>{});assert.equal((await request('owner',`/${canonBranch.body.branch.id}/fragments/${canonFragment.body.branch.fragments[0].id}/merge`,'POST',{...mergeInput,acknowledgeCanonChange:'false'})).status,409);
const issuesBefore=await repo.listContinuityIssues(P);await request('owner',`/${canonBranch.body.branch.id}/check`,'POST',{});assert.deepEqual(await repo.listContinuityIssues(P),issuesBefore);n++;
const beforeBrowser=branchHash((await getBook(P))!.book);
if(process.argv.includes('--browser')){
 const {build}=await import('esbuild');const output=await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import{BranchesPage}from'./src/components/BranchesPage';createRoot(document.getElementById('root')).render(React.createElement(BranchesPage,{book:{id:${JSON.stringify(P)}}}));`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,format:'iife',platform:'browser'});
 const css=(await Promise.all((await fs.readdir('dist/assets')).filter(x=>x.endsWith('.css')).map(x=>fs.readFile(path.join('dist/assets',x),'utf8')))).join('\n');app.get('/probe.css',(_q,r)=>r.type('text/css').send(css));app.get('/probe.js',(_q,r)=>r.type('application/javascript').send(output.outputFiles[0].text));app.get('/probe',(_q,r)=>r.send('<meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/probe.css"><div id="root"></div><script src="/probe.js"></script>'));
 const puppeteer=await import('puppeteer-core');const browser=await puppeteer.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{const page=await browser.newPage();await page.setViewport({width:390,height:844});await page.goto(origin+'/probe');await page.waitForSelector('[aria-label="Гілка"]');await page.select('[aria-label="Гілка"]',response.body.branch.id);await page.waitForSelector('[aria-label="Текст альтернативи"]');await page.select('[aria-label="Сцена гілки"]','s');await page.type('[aria-label="Текст альтернативи"]','Браузерна альтернатива.');for(const button of await page.$$('button'))if((await button.evaluate(x=>x.textContent))==='Зберегти ізольовану чернетку'){await button.click();break;}
 await page.waitForFunction(()=>document.querySelector('article')?.textContent?.includes('Браузерна альтернатива.'));check('БРАУЗЕР: автор зберігає ізольований фрагмент',()=>{});assert.equal(branchHash((await getBook(P))!.book),beforeBrowser);n++;check('БРАУЗЕР: кнопка перенесення вимагає підтвердження',()=>{});assert.equal(await page.$$eval('button',xs=>(xs.find(x=>x.textContent==='Підтвердити цей фрагмент у рукопис') as HTMLButtonElement)?.disabled),true);check('БРАУЗЕР: сторінка вміщується на телефоні',()=>{});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:`/tmp/branches-${repo.kind}.png`,fullPage:true});}finally{await browser.close();}
}
}finally{await new Promise<void>(r=>server.close(()=>r()));}
console.log(`${repo.kind}: ${n} перевірок пройшло.`);
}
try{await suite(new MemoryCoreRepository());if(process.env.CORE_TEST_DATABASE_URL){const pool=createCorePool(process.env.CORE_TEST_DATABASE_URL);try{await runMigrations(pool,loadMigrations(resolveMigrationsDir()));await suite(new PgCoreRepository(pool));}finally{await pool.end();}}}finally{await fs.rm(dir,{recursive:true,force:true});}
