import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {MemoryCoreRepository} from '../server/core/memoryRepository';
import {PgCoreRepository} from '../server/core/pgRepository';
import type {CoreRepository} from '../server/core/types';
import {createCorePool} from '../server/core';
import {loadMigrations,resolveMigrationsDir,runMigrations} from '../server/core/migrate';
import {createBookToolRuntime,createBookTools,BOOK_TOOL_NAMES,type BookToolScope} from '../server/ai/tools';
import {InProcessAgentRuntime,ToolDeniedError} from '../server/ai/adapters/harness';
import {BOOK_SKILLS,skillInstructions} from '../server/ai/skills';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'book-tools-'));
process.env.DATA_DIR=dir;process.env.DATABASE_PATH=path.join(dir,'test.db');
const {saveBook,getBook}=await import('../server/bookStore');
const {syncBookToCore}=await import('../server/core/sync');
const {startMagic,stepMagic}=await import('../server/core/magicScene');
const {branchHash,branchCanonHash}=await import('../server/core/branches');
const {acceptProposal}=await import('../server/core/interviewProposals');
async function suite(repo:CoreRepository){
 let count=0;const check=async(label:string,fn:()=>unknown|Promise<unknown>)=>{await fn();count++;console.log(`✓ ${label}`);};
 const projectId='tools-'+randomUUID(),actor='user:owner' as const;
 const book=await saveBook({ownerId:'owner',book:{id:projectId,title:'Tools',chapters:[{id:'ch',sections:[{id:'past',content:'Попередня зустріч.'},{id:'scene',content:'Герої зустрілися в кімнаті.'},{id:'other-scene',content:'Інша сцена.'},{id:'future',content:'Пізніша подія.'}]}]} as any});await syncBookToCore(repo,book);
 const heroes=[];for(const name of ['Олена','Марко']){const h=await repo.createEntity({projectId,type:'character',name,status:'confirmed',createdBy:actor});heroes.push(h);await repo.upsertCharacterAgent({projectId,characterId:h.id,autonomyLevel:'scene',actor,agentConfig:{}});}
 const [own,other]=heroes;
 const outsider=await repo.createEntity({projectId,type:'character',name:'Анна',status:'confirmed',createdBy:actor});
 for(const [h,sceneId,text] of [[own,'past','ВЛАСНА_ПАМʼЯТЬ'],[other,'past','ЧУЖА_ПАМʼЯТЬ'],[own,'future','МАЙБУТНЄ_ЗНАННЯ']] as const)await repo.addCharacterMemory({projectId,characterId:h.id,memoryType:'knowledge',content:text,sceneId,canonRevision:(await repo.getProject(projectId))!.revision,sourceEventKind:'author',origin:'author',status:'confirmed',visibility:'hidden',createdBy:actor});
 let run=await startMagic(repo,projectId,'scene',{participants:heroes.map(h=>h.id),goal:'Обговорити лист',constraints:'Лише видимі дії',maxTurns:6},actor);
 const engines={repo,decide:async()=>({action:'answer',source:'mock'}),voice:async(c:any)=>({speech:c.hero.id===own.id?'ВЛАСНА_РЕПЛІКА':'НЕПОЧУТА_РЕПЛІКА',actionText:'Показує лист.',privateThought:'ПРИВАТНА_ДУМКА',intent:'Приховати страх',audience:[c.hero.id]}),writer:async()=>({})};
 run=await stepMagic(engines,projectId,run.simulationId,{expectedRevision:run.revision,requestId:randomUUID()},actor);
 run=await stepMagic(engines,projectId,run.simulationId,{expectedRevision:run.revision,requestId:randomUUID()},actor);
 const scope:BookToolScope={projectId,actorId:actor,characterId:own.id,sceneId:'scene',simulationId:run.simulationId};
 let granted=true,evaluation:any={action:'answer',source:'fixture'};
 const deps={repo,scope,authorize:async s=>granted&&s.actorId===actor&&s.projectId===projectId,allowedActions:['answer','silence'],situation:'Обговорити лист',evaluate:async()=>evaluation};
 const runtime=createBookToolRuntime(deps);
 const call=(name:string,args?:unknown)=>runtime.step('character-agent',[name],ctx=>ctx.tool<any>(name,args));
 const unchanged=async()=>branchHash({book:(await getBook(projectId))!.book,canon:await branchCanonHash(repo,projectId),memories:await repo.listCharacterMemories(projectId,{limit:1000}),findings:await repo.listFindings(projectId)});
 const before=await unchanged();
 await check('сім skills завантажуються з фіксованого каталогу',()=>{assert.equal(BOOK_SKILLS.length,7);for(const skill of BOOK_SKILLS){const instructions=skillInstructions([skill]);assert.ok(instructions.includes('pending'));assert.ok(instructions.includes('simulation_id'));assert.ok(instructions.length>500);}});
 await check('невідомий skill не читає довільний файл',()=>assert.throws(()=>skillInstructions(['../../AGENTS.md' as any])));
 await check('реєстр містить лише сім книжкових tools',()=>assert.equal(BOOK_TOOL_NAMES.length,7));
 for(const key of ['project_id','actor_id','character_id','scene_id','simulation_id','projectId','actorId','characterId','sceneId','simulationId'])await check(`підміна ${key} заборонена`,()=>assert.rejects(()=>call('get-character-snapshot',{[key]:'foreign'}),ToolDeniedError));
 await check('підміна вкладених параметрів заборонена',()=>assert.rejects(()=>call('get-character-snapshot',{scope:{character_id:other.id}}),ToolDeniedError));
 await check('параметри поточного scope дозволені',async()=>assert.equal((await call('get-character-snapshot',{character_id:own.id,scene_id:'scene'})).snapshot.character_id,own.id));
 await check('знімок не розкриває чужу памʼять чи майбутнє',async()=>{const text=JSON.stringify(await call('get-character-snapshot'));assert.ok(text.includes('ВЛАСНА_ПАМʼЯТЬ'));assert.ok(!text.includes('ЧУЖА_ПАМʼЯТЬ'));assert.ok(!text.includes('МАЙБУТНЄ_ЗНАННЯ'));});
 await check('контекст сцени містить лише власні спостережувані події',async()=>{const context=await call('get-scene-context');assert.equal(context.observed.length,1);assert.ok(!JSON.stringify(context).includes('НЕПОЧУТА_РЕПЛІКА'));assert.ok(!JSON.stringify(context).includes('ПРИВАТНА_ДУМКА'));});
 await check('пошук не розширює межу знань',async()=>assert.deepEqual(await call('search-character-mentions',{query:'МАЙБУТНЄ'}),[]));
 await check('оцінювання приймає тільки дозволені дії',async()=>assert.equal((await call('evaluate-character-options',{actions:['answer']})).action,'answer'));
 await check('невідома дія не потрапляє до адаптера',()=>assert.rejects(()=>call('evaluate-character-options',{actions:['delete-canon']}),ToolDeniedError));
 evaluation={action:'delete-canon'};await check('некоректна відповідь адаптера відхиляється',()=>assert.rejects(()=>call('evaluate-character-options')));evaluation={action:'answer'};
 granted=false;await check('відкликання доступу діє на наступний tool',()=>assert.rejects(()=>call('get-character-snapshot'),ToolDeniedError));granted=true;
 for(const name of ['shell','filesystem','fetch','read-file','accept-canon-change','resolve-canon-proposal'])await check(`${name} не зареєстровано`,()=>assert.rejects(()=>call(name),ToolDeniedError));
 await check('tool поза списком конкретного агента заблоковано',()=>assert.rejects(()=>runtime.step('writer',[],ctx=>ctx.tool('get-character-snapshot')),ToolDeniedError));
 await check('без Vault таємниця недоступна',()=>assert.rejects(()=>call('read-authorized-secret',{secretId:'secret'}),ToolDeniedError));
 const signal=new AbortController();
 await check('прямий виклик tool із чужим scope заборонений',()=>assert.rejects(()=>createBookTools(deps)[0].run({}, {...scope,characterId:other.id},signal.signal),ToolDeniedError));
 const wrongScene=createBookToolRuntime({...deps,scope:{...scope,sceneId:'other-scene'}});
 await check('навіть збіг аргументів не дозволяє чужу сцену прогону',()=>assert.rejects(()=>wrongScene.step('agent',['get-scene-context'],ctx=>ctx.tool('get-scene-context')),ToolDeniedError));
 const absentHero=createBookToolRuntime({...deps,scope:{...scope,characterId:outsider.id}});
 await check('неучасник прогону не отримує знімок',()=>assert.rejects(()=>absentHero.step('agent',['get-character-snapshot'],ctx=>ctx.tool('get-character-snapshot')),ToolDeniedError));
 const tampered={...scope};const fixed=new InProcessAgentRuntime(tampered,createBookTools(deps));tampered.characterId=other.id;
 await check('зовнішня зміна обʼєкта scope не впливає на рантайм',async()=>assert.equal((await fixed.step('agent',['get-character-snapshot'],ctx=>ctx.tool<any>('get-character-snapshot'))).snapshot.character_id,own.id));
 const note=await call('write-simulation-event',{text:'Власна нотатка прогону'});
 await check('запис є лише подією власного прогону',()=>{assert.equal(note.simulationId,scope.simulationId);assert.equal(note.actorCharacterId,own.id);assert.equal(note.createdBy,actor);});
 await check('tool не може записати подію від імені автора',()=>assert.rejects(()=>call('write-simulation-event',{text:'Підміна',actor:'author'}),ToolDeniedError));
 await check('подія й читання не змінили книгу, канон чи памʼять',async()=>assert.equal(await unchanged(),before));
 const memory=await call('propose-canon-change',{kind:'memory',text:'Герой запамʼятав лист.',sourceEventIds:[run.events[0].id]});
 await check('propose-canon-change створює тільки pending-пропозицію',async()=>{assert.equal(memory.status,'pending');assert.equal(memory.reviewedBy,null);assert.equal(memory.characterId,own.id);assert.equal(await unchanged(),before);});
 await check('agent не може передати confirm чи accepted',()=>assert.rejects(()=>call('propose-canon-change',{kind:'memory',text:'Обхід',sourceEventIds:[note.id],confirm:true,status:'accepted'}),ToolDeniedError));
 await check('непочута подія не є доказом пропозиції',()=>assert.rejects(()=>call('propose-canon-change',{kind:'memory',text:'Обхід',sourceEventIds:[run.events[1].id]})));
 await check('підміна героя під час пропозиції заборонена',()=>assert.rejects(()=>call('propose-canon-change',{character_id:other.id,kind:'memory',text:'Обхід',sourceEventIds:[run.events[0].id]}),ToolDeniedError));
 const fragment=await call('propose-canon-change',{kind:'fragment',text:'Герой прочитав лист. [/emotion:страх @Олена]',sourceEventIds:[run.events[0].id]});
 await check('текст пропозиції очищено від автоматичних тегів',()=>assert.ok(!fragment.proposedChange.text.includes('[/emotion:')));
 const tag=await call('propose-canon-change',{kind:'tag',text:'[/emotion:страх @Олена]',parentId:fragment.id,sourceEventIds:[run.events[0].id]});
 await check('тег — лише pending до власного фрагмента',()=>{assert.equal(tag.parentId,fragment.id);assert.equal(tag.status,'pending');});
 await check('тег без власного фрагмента відхиляється',()=>assert.rejects(()=>call('propose-canon-change',{kind:'tag',text:'[/emotion:страх @Олена]',parentId:memory.id,sourceEventIds:[run.events[0].id]})));
 const foreignFragment=await repo.addCanonProposal({projectId,simulationId:run.simulationId,characterId:other.id,kind:'fragment',proposedChange:{text:'Чужий фрагмент'},sourceEventIds:[run.events[1].id],createdBy:'ai:character-voice'});
 await check('тег не можна привʼязати до чужої пропозиції',()=>assert.rejects(()=>call('propose-canon-change',{kind:'tag',text:'[/emotion:страх @Олена]',parentId:foreignFragment.id,sourceEventIds:[run.events[0].id]})));
 await check('наявний маршрут затвердження відхиляє актора AI',()=>assert.rejects(()=>acceptProposal(repo,{projectId,proposalId:memory.id,actor:'ai:character-voice'})));
 await check('усі пропозиції досі не змінили канон',async()=>assert.equal(await unchanged(),before));
 await check('tool не виконується після завершення кроку',async()=>{let retained:any;await runtime.step('agent',['get-character-snapshot'],async ctx=>{retained=ctx;});await assert.rejects(()=>retained.tool('get-character-snapshot'),ToolDeniedError);});
 await check('ліміт викликів застосовується',()=>assert.rejects(()=>runtime.step('agent',['get-scene-context'],async ctx=>{await ctx.tool('get-scene-context');await ctx.tool('get-scene-context');},{maxToolCalls:1}),ToolDeniedError));
 const abort=new AbortController();abort.abort();await check('скасований tool не додає подію',async()=>{const beforeNotes=(await repo.listSimulationEvents(projectId,scope.simulationId)).length;await assert.rejects(()=>createBookTools(deps).find(t=>t.name==='write-simulation-event')!.run({text:'Не записати'},scope,abort.signal));assert.equal((await repo.listSimulationEvents(projectId,scope.simulationId)).length,beforeNotes);});
 await check('зміна аргументів під час авторизації не підміняє героя',async()=>{
  let release:(ok:boolean)=>void;
  const delayed=createBookToolRuntime({...deps,authorize:async()=>new Promise<boolean>(r=>{release=r;})});
  const args={character_id:own.id};const pending=delayed.step('agent',['get-character-snapshot'],ctx=>ctx.tool<any>('get-character-snapshot',args));
  args.character_id=other.id;release!(true);assert.equal((await pending).snapshot.character_id,own.id);
 });
 await check('запізніла авторизація після тайм-ауту не записує подію',async()=>{
  let release:(ok:boolean)=>void;
  const delayed=createBookToolRuntime({...deps,authorize:async()=>new Promise<boolean>(r=>{release=r;})});
  const notes=(await repo.listSimulationEvents(projectId,scope.simulationId)).length;
  await assert.rejects(()=>delayed.step('agent',['write-simulation-event'],ctx=>ctx.tool('write-simulation-event',{text:'Не записати'}),{timeoutMs:5}));
  release!(true);await new Promise(r=>setTimeout(r,20));assert.equal((await repo.listSimulationEvents(projectId,scope.simulationId)).length,notes);
 });
 await check('Magic Scene зберігає трасу реальних tools',()=>assert.deepEqual(run.privateSteps[0].toolTrace?.filter(e=>e.kind==='tool_call').map(e=>e.tool),['get-character-snapshot','get-scene-context','evaluate-character-options']));
 console.log(`${repo.kind}: ${count} перевірок пройшло.`);
}
try{await suite(new MemoryCoreRepository());if(process.env.CORE_TEST_DATABASE_URL){const pool=createCorePool(process.env.CORE_TEST_DATABASE_URL);try{await runMigrations(pool,loadMigrations(resolveMigrationsDir()));await suite(new PgCoreRepository(pool));}finally{await pool.end();}}}finally{await fs.rm(dir,{recursive:true,force:true});}
